PokemonMansion_1F_Text_TedIntro::
    .string "Who are you?\n"
    .string "There shouldn't be anyone here.$"

PokemonMansion_1F_Text_TedDefeat::
    .string "Ouch!$"

PokemonMansion_1F_Text_TedPostBattle::
    .string "A key? I don't know what you're\n"
    .string "talking about.$"

PokemonMansion_1F_Text_JohnsonIntro::
    .string "This building is unstable.\n"
    .string "My research is not.$"

PokemonMansion_1F_Text_JohnsonDefeat::
    .string "My data collapsed!$"

PokemonMansion_1F_Text_JohnsonPostBattle::
    .string "Every scorched wall here tells\n"
    .string "part of CINNABAR's story.$"
