SaffronCity_MrPsychicsHouse_Text_YouWantedThis::
    .string "…Wait! Don't say a word!\p"
    .string "You came seeking power.\n"
    .string "I can sense it.$"

SaffronCity_MrPsychicsHouse_Text_ReceivedTM29FromMrPsychic::
    .string "{PLAYER} received TM29\n"
    .string "from MR. PSYCHIC.$"

SaffronCity_MrPsychicsHouse_Text_ExplainTM29::
    .string "You already know, don't you?\p"
    .string "Power alone will not carry you.$"

SaffronCity_MrPsychicsHouse_Text_YouveNoRoom::
    .string "Where do you plan to put this?\n"
    .string "You've no room.$"
