MtMoon_1F_Text_MarcosIntro::
    .string "WHOA!\n"
    .string "You shocked me!\l"
    .string "…Oh, you're just a kid!$"

MtMoon_1F_Text_MarcosDefeat::
    .string "Hah!\n"
    .string "You hit harder than loose rock!$"

MtMoon_1F_Text_MarcosPostBattle::
    .string "Kids like you shouldn't be\n"
    .string "wandering around here in the dark.$"

MtMoon_1F_Text_JoshIntro::
    .string "Did you come to explore the cave,\n"
    .string "too?$"

MtMoon_1F_Text_JoshDefeat::
    .string "Losing stinks!\n"
    .string "It's so uncool.$"

MtMoon_1F_Text_JoshPostBattle::
    .string "I came all the way down here to\n"
    .string "show off to girls.$"

MtMoon_1F_Text_MiriamIntro::
    .string "Wow! It's way bigger in here than\n"
    .string "I thought!$"

MtMoon_1F_Text_MiriamDefeat::
    .string "Oh!\n"
    .string "This cave really is full of\n"
    .string "surprises.$"

MtMoon_1F_Text_MiriamPostBattle::
    .string "How do you get out of here?\n"
    .string "It's so big, I may get lost.$"

MtMoon_1F_Text_JovanIntro::
    .string "What!\n"
    .string "Don't sneak up on me!$"

MtMoon_1F_Text_JovanDefeat::
    .string "My POKéMON won't do!$"

MtMoon_1F_Text_JovanPostBattle::
    .string "I have to find stronger POKéMON.\n"
    .string "Where might they be?$"

MtMoon_1F_Text_IrisIntro::
    .string "What?\n"
    .string "I'm waiting for my friends to find\l"
    .string "me here.$"

MtMoon_1F_Text_IrisDefeat::
    .string "I waited here and still wasn't\n"
    .string "ready for you.$"

MtMoon_1F_Text_IrisPostBattle::
    .string "I came because I heard there are\n"
    .string "some very rare fossils here.$"

MtMoon_1F_Text_KentIntro::
    .string "I heard rare fossils are in here.\n"
    .string "What about you?$"

MtMoon_1F_Text_KentDefeat::
    .string "You found my weak spot faster than\n"
    .string "I found a fossil.$"

MtMoon_1F_Text_KentPostBattle::
    .string "I saw some glittering stones,\n"
    .string "but I couldn't tell what they were.$"

MtMoon_1F_Text_RobbyIntro::
    .string "You need to go through this cave\n"
    .string "to get to CERULEAN CITY.$"

MtMoon_1F_Text_RobbyDefeat::
    .string "Even the cave echoes know I lost.$"

MtMoon_1F_Text_RobbyPostBattle::
    .string "ZUBAT is tough!\n"
    .string "But if you can catch one, you'll\l"
    .string "be able to count on it.$"

MtMoon_1F_Text_ZubatIsABloodsucker::
    .string "Beware!\n"
    .string "ZUBAT is a bloodsucker!$"

MtMoon_1F_Text_BrockHelpsExcavateFossils::
    .string "Hi, I'm excavating for fossils here\n"
    .string "under MT. MOON.\p"
    .string "Sometimes, BROCK of PEWTER GYM\n"
    .string "lends me a hand.$"

MtMoon_1F_Text_AngryPrimalPokemon::
    .string "There's something furious and\n"
    .string "hurt deep within this cave.\p"
    .string "I can feel it losing control.\n"
    .string "Maybe I should head home.$"
