PokemonMansion_B1F_Text_LewisIntro::
    .string "Uh-oh…\n"
    .string "Where am I now?$"

PokemonMansion_B1F_Text_LewisDefeat::
    .string "Awooh!$"

PokemonMansion_B1F_Text_LewisPostBattle::
    .string "You can find stuff lying around.\n"
    .string "The residents must've left them.$"

PokemonMansion_B1F_Text_IvanIntro::
    .string "This place is ideal for a lab.\n"
    .string "Look at all this space.$"

PokemonMansion_B1F_Text_IvanDefeat::
    .string "What was that for?$"

PokemonMansion_B1F_Text_IvanPostBattle::
    .string "I like it here.\n"
    .string "It's conducive to my studies.$"

PokemonMansion_B1F_Text_MewtwoIsFarTooPowerful::
    .string "Diary: Sept. 1\n"
    .string "MEWTWO is far too powerful.\p"
    .string "We have failed to curb its vicious\n"
    .string "tendencies…$"

PokemonMansion_B1F_Text_GiovanniIntro::
    .string "GIOVANNI: Empty…\n"
    .string "After all these years, empty.\p"
    .string "This shattered vat was meant to\n"
    .string "hold the perfect POKéMON.\p"
    .string "Power without waste.\n"
    .string "Power without weakness.\p"
    .string "MEWTWO broke free before it could\n"
    .string "be claimed.\p"
    .string "No matter.\n"
    .string "I built that power once.\p"
    .string "I will retrieve it, perfect it,\n"
    .string "and make it mine.$"
