CinnabarIsland_PokemonLab_Lounge_Text_FoundFossilInMtMoon::
    .string "I found this most remarkable fossil\n"
    .string "inside MT. MOON.\p"
    .string "I think it's of a rare, prehistoric\n"
    .string "POKéMON.$"

CinnabarIsland_PokemonLab_Lounge_Text_ElectricTradeMoved::
    .string "Electric POKéMON are fascinating.\p"
    .string "Their evolution can change with\n"
    .string "the right kind of energy.$"
