SafariZone_SecretHouse_Text_CongratsYouveWon::
    .string "Ah! Finally!\p"
    .string "You're the first person to reach\n"
    .string "the SECRET HOUSE!\p"
    .string "Congratulations!\n"
    .string "You made it!$"

SafariZone_SecretHouse_Text_ReceivedTM53FromAttendant::
    .string "{PLAYER} received TM53\n"
    .string "from the attendant!$"

SafariZone_SecretHouse_Text_ExplainSurf::
    .string "It's not easy getting here.\n"
    .string "You should be proud.$"

SafariZone_SecretHouse_Text_DontHaveRoomForPrize::
    .string "You don't have room for this\n"
    .string "fabulous prize!$"
