Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests::
    .string "Many POKéMON live only in forests \n"
    .string "and caves.\p"
    .string "You need to be persistent and look\n"
    .string "everywhere to get different kinds.$"

Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees::
    .string "Have you noticed how many kinds\n"
    .string "of trees grow around here?\p"
    .string "Forests are full of little clues\n"
    .string "about nearby POKéMON, I hear.$"

Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution::
    .string "Do you know the evolution-cancel\n"
    .string "technique?\p"
    .string "When a POKéMON is evolving, you\n"
    .string "can stop the process.\p"
    .string "It's a technique for raising\n"
    .string "POKéMON the way they are.$"
