#ifndef GUARD_CONSTANTS_APEX_LOG_H
#define GUARD_CONSTANTS_APEX_LOG_H

#define APEX_LOG_PERSON_OAK          0
#define APEX_LOG_PERSON_DAISY        1
#define APEX_LOG_PERSON_BROCK        2
#define APEX_LOG_PERSON_MISTY        3
#define APEX_LOG_PERSON_LTSURGE      4
#define APEX_LOG_PERSON_ERIKA        5
#define APEX_LOG_PERSON_KOGA         6
#define APEX_LOG_PERSON_SABRINA      7
#define APEX_LOG_PERSON_BLAINE       8
#define APEX_LOG_PERSON_LORELEI      9
#define APEX_LOG_PERSON_BRUNO       10
#define APEX_LOG_PERSON_AGATHA      11
#define APEX_LOG_PERSON_LANCE       12
#define APEX_LOG_PERSON_BILL        13
#define APEX_LOG_PERSON_MRFUJI      14
#define APEX_LOG_PERSON_GIOVANNI    15
#define NUM_APEX_LOG_PERSONS 16

#define APEX_LOG_PICK_STATE_NO_DRAW    0
#define APEX_LOG_PICK_STATE_SILHOUETTE 1
#define APEX_LOG_PICK_STATE_COLORED    2

#endif //GUARD_CONSTANTS_APEX_LOG_H
