#ifndef GUARD_CONSTANTS_MYSTERY_GIFT_H
#define GUARD_CONSTANTS_MYSTERY_GIFT_H

#define GET_NUM_STAMPS        0
#define GET_MAX_STAMPS        1
#define GET_CARD_BATTLES_WON  2
#define GET_CARD_BATTLES_LOST 3
#define GET_CARD_NUM_TRADES   4

#define CARD_STAT_BATTLES_WON   0
#define CARD_STAT_BATTLES_LOST  1
#define CARD_STAT_NUM_TRADES    2
#define CARD_STAT_NUM_STAMPS    3
#define CARD_STAT_MAX_STAMPS    4

#endif //GUARD_CONSTANTS_MYSTERY_GIFT_H
