#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#define TRAINER_NONE                               0
#define TRAINER_JUGGLER_KAYDEN_2                   TRAINER_NONE
// Dummy trainers for all the RS trainer classes
#define TRAINER_AQUA_LEADER                        1
#define TRAINER_AQUA_GRUNT_M                       2
#define TRAINER_AQUA_GRUNT_F                       3
#define TRAINER_RS_AROMA_LADY                      4
#define TRAINER_RS_RUIN_MANIAC                     5
#define TRAINER_RS_TUBER_F                         7
#define TRAINER_RS_TUBER_M                         8
#define TRAINER_RS_COOLTRAINER_M                   9
#define TRAINER_RS_COOLTRAINER_F                  10
#define TRAINER_HEX_MANIAC                        11
#define TRAINER_RS_LADY                           12
#define TRAINER_RS_BEAUTY                         13
#define TRAINER_RICH_BOY                          14
#define TRAINER_RS_POKEMANIAC                     15
#define TRAINER_RS_SWIMMER_M                      16
#define TRAINER_RS_BLACK_BELT                     17
#define TRAINER_GUITARIST                         18
#define TRAINER_KINDLER                           19
#define TRAINER_RS_CAMPER                         20
#define TRAINER_BUG_MANIAC                        21
#define TRAINER_RS_PSYCHIC_M                      22
#define TRAINER_RS_PSYCHIC_F                      23
#define TRAINER_RS_GENTLEMAN                      24
#define TRAINER_ELITE_FOUR_SIDNEY                 25
#define TRAINER_ELITE_FOUR_PHOEBE                 26
#define TRAINER_LEADER_ROXANNE                    27
#define TRAINER_LEADER_BRAWLY                     28
#define TRAINER_LEADER_TATE_LIZA                  29
#define TRAINER_SCHOOL_KID_M                      30
#define TRAINER_SCHOOL_KID_F                      31
#define TRAINER_SR_AND_JR                         32
#define TRAINER_POKEFAN_M                         33
#define TRAINER_POKEFAN_F                         34
#define TRAINER_EXPERT_M                          35
#define TRAINER_EXPERT_F                          36
#define TRAINER_RS_YOUNGSTER                      37
#define TRAINER_RS_CHAMPION                       38
#define TRAINER_RS_FISHERMAN                      39
#define TRAINER_CYCLING_TRIATHLETE_M              40
#define TRAINER_CYCLING_TRIATHLETE_F              41
#define TRAINER_RUNNING_TRIATHLETE_M              42
#define TRAINER_RUNNING_TRIATHLETE_F              43
#define TRAINER_SWIMMING_TRIATHLETE_M             44
#define TRAINER_SWIMMING_TRIATHLETE_F             45
#define TRAINER_DRAGON_TAMER                      46
#define TRAINER_RS_BIRD_KEEPER                    47
#define TRAINER_NINJA_BOY                         48
#define TRAINER_BATTLE_GIRL                       49
#define TRAINER_PARASOL_LADY                      50
#define TRAINER_RS_SWIMMER_F                      51
#define TRAINER_RS_PICNICKER                      52
#define TRAINER_RS_TWINS                          53
#define TRAINER_RS_SAILOR                         54
#define TRAINER_COLLECTOR                         57
#define TRAINER_WALLY                             58
#define TRAINER_UNUSED_59                         59
#define TRAINER_UNUSED_60                         60
#define TRAINER_UNUSED_61                         61
#define TRAINER_UNUSED_62                         62
#define TRAINER_UNUSED_63                         63
#define TRAINER_UNUSED_64                         64
#define TRAINER_RS_PKMN_BREEDER_M                 65
#define TRAINER_RS_PKMN_BREEDER_F                 66
#define TRAINER_RS_PKMN_RANGER_M                  67
#define TRAINER_RS_PKMN_RANGER_F                  68
#define TRAINER_MAGMA_LEADER                      69
#define TRAINER_MAGMA_GRUNT_M                     70
#define TRAINER_MAMGA_GRUNT_F                     71
#define TRAINER_RS_LASS                           72
#define TRAINER_RS_BUG_CATCHER                    73
#define TRAINER_RS_HIKER                          74
#define TRAINER_RS_YOUNG_COUPLE                   75
#define TRAINER_OLD_COUPLE                        76
#define TRAINER_RS_SIS_AND_BRO                    77
#define TRAINER_AQUA_ADMIN_MATT                   78
#define TRAINER_AQUA_ADMIN_SHELLY                 79
#define TRAINER_MAGMA_ADMIN_TABITHA               80
#define TRAINER_MAGMA_ADMIN_COURTNEY              81
#define TRAINER_LEADER_WATTSON                    82
#define TRAINER_LEADER_FLANNERY                   83
#define TRAINER_LEADER_NORMAN                     84
#define TRAINER_LEADER_WINONA                     85
#define TRAINER_LEADER_WALLACE                    86
#define TRAINER_ELITE_FOUR_GLACIA                 87
#define TRAINER_ELITE_FOUR_DRAKE                  88
// Actual FRLG trainers start here
#define TRAINER_YOUNGSTER_BEN                     89
#define TRAINER_JUGGLER_SHAWN_2                    TRAINER_YOUNGSTER_BEN
#define TRAINER_YOUNGSTER_CALVIN                  90
#define TRAINER_JUGGLER_KIRK_2                     TRAINER_YOUNGSTER_CALVIN
#define TRAINER_YOUNGSTER_JOSH                    91
#define TRAINER_YOUNGSTER_TIMMY                   92
#define TRAINER_TAMER_EDGAR_2                      TRAINER_YOUNGSTER_TIMMY
#define TRAINER_YOUNGSTER_JOEY                    93
#define TRAINER_TAMER_PHIL_2                       TRAINER_YOUNGSTER_JOEY
#define TRAINER_YOUNGSTER_DAN                     94
#define TRAINER_JUGGLER_NATE_2                     TRAINER_YOUNGSTER_DAN
#define TRAINER_YOUNGSTER_CHAD                    95
#define TRAINER_BUG_CATCHER_ROBBY_2                TRAINER_YOUNGSTER_CHAD
#define TRAINER_YOUNGSTER_TYLER                   96
#define TRAINER_YOUNGSTER_EDDIE                   97
#define TRAINER_SUPER_NERD_JOVAN_2                 TRAINER_YOUNGSTER_EDDIE
#define TRAINER_YOUNGSTER_DILLON                  98
#define TRAINER_BUG_CATCHER_KENT_2                 TRAINER_YOUNGSTER_DILLON
#define TRAINER_YOUNGSTER_YASU                    99
#define TRAINER_HIKER_MARCOS_2                     TRAINER_YOUNGSTER_YASU
#define TRAINER_YOUNGSTER_DAVE                   100
#define TRAINER_SCIENTIST_TED_2                    TRAINER_YOUNGSTER_DAVE
#define TRAINER_YOUNGSTER_BEN_2                  101
#define TRAINER_BURGLAR_ARNIE_2                    TRAINER_YOUNGSTER_BEN_2
#define TRAINER_BUG_CATCHER_RICK                 102
#define TRAINER_BUG_CATCHER_DOUG                 103
#define TRAINER_BUG_CATCHER_SAMMY                104
#define TRAINER_BUG_CATCHER_COLTON               105
#define TRAINER_BURGLAR_SIMON_2                    TRAINER_BUG_CATCHER_COLTON
#define TRAINER_BUG_CATCHER_GREG                 106
#define TRAINER_SCIENTIST_BRAYDON_2                TRAINER_BUG_CATCHER_GREG
#define TRAINER_BUG_CATCHER_JAMES                107
#define TRAINER_SCIENTIST_IVAN_2                   TRAINER_BUG_CATCHER_JAMES
#define TRAINER_BUG_CATCHER_KENT                 108
#define TRAINER_BUG_CATCHER_ROBBY                109
#define TRAINER_BUG_CATCHER_CALE                 110
#define TRAINER_CHANNELER_PATRICIA_2               TRAINER_BUG_CATCHER_CALE
#define TRAINER_BUG_CATCHER_KEIGO                111
#define TRAINER_CHANNELER_CARLY_2                  TRAINER_BUG_CATCHER_KEIGO
#define TRAINER_BUG_CATCHER_ELIJAH               112
#define TRAINER_CHANNELER_HOPE_2                   TRAINER_BUG_CATCHER_ELIJAH
#define TRAINER_BUG_CATCHER_OWEN                 113
#define TRAINER_CAMPER_LIAM_2 TRAINER_BUG_CATCHER_OWEN
#define TRAINER_CHANNELER_LAUREL_2                 TRAINER_CAMPER_LIAM_2
#define TRAINER_BUG_CATCHER_BRENT                114
#define TRAINER_CHANNELER_JODY_2                   TRAINER_BUG_CATCHER_BRENT
#define TRAINER_BUG_CATCHER_CONNER               115
#define TRAINER_CHANNELER_PAULA_2                  TRAINER_BUG_CATCHER_CONNER
#define TRAINER_LASS_JANICE                      116
#define TRAINER_CHANNELER_RUTH_2                   TRAINER_LASS_JANICE
#define TRAINER_LASS_SALLY                       117
#define TRAINER_CHANNELER_TAMMY_2                  TRAINER_LASS_SALLY
#define TRAINER_LASS_ROBIN                       118
#define TRAINER_CHANNELER_JANAE_2                  TRAINER_LASS_ROBIN
#define TRAINER_LASS_CRISSY                      119
#define TRAINER_CHANNELER_ANGELICA_2               TRAINER_LASS_CRISSY
#define TRAINER_LASS_MIRIAM                      120
#define TRAINER_LASS_IRIS                        121
#define TRAINER_LASS_RELI                        122
#define TRAINER_CHANNELER_JENNIFER_2               TRAINER_LASS_RELI
#define TRAINER_LASS_ALI                         123
#define TRAINER_CHANNELER_EMILIA_2                 TRAINER_LASS_ALI
#define TRAINER_LASS_NORA                        124
#define TRAINER_HIKER_LUCAS_2                      TRAINER_LASS_NORA
#define TRAINER_LASS_HALEY                       125
#define TRAINER_HIKER_OLIVER_2                     TRAINER_LASS_HALEY
#define TRAINER_LASS_ANN                         126
#define TRAINER_LASS_DAWN                        127
#define TRAINER_LASS_PAIGE                       128
#define TRAINER_HIKER_LENNY_2                      TRAINER_LASS_PAIGE
#define TRAINER_LASS_ANDREA                      129
#define TRAINER_POKEMANIAC_ASHTON_2                TRAINER_LASS_ANDREA
#define TRAINER_LASS_MEGAN                       130
#define TRAINER_POKEMANIAC_COOPER_2                TRAINER_LASS_MEGAN
#define TRAINER_LASS_JULIA                       131
#define TRAINER_HIKER_DUDLEY_2                     TRAINER_LASS_JULIA
#define TRAINER_LASS_KAY                         132
#define TRAINER_LASS_LISA                        133
#define TRAINER_SAILOR_EDMOND                    134
#define TRAINER_SAILOR_TREVOR                    135
#define TRAINER_SAILOR_LEONARD                   136
#define TRAINER_SAILOR_DUNCAN                    137
#define TRAINER_SAILOR_HUEY                      138
#define TRAINER_SAILOR_DYLAN                     139
#define TRAINER_SAILOR_PHILLIP                   140
#define TRAINER_SAILOR_DWAYNE                    141
#define TRAINER_CAMPER_LIAM                      142
#define TRAINER_HIKER_ALLEN_2                      TRAINER_CAMPER_LIAM
#define TRAINER_CAMPER_SHANE                     143
#define TRAINER_HIKER_ERIC_2                       TRAINER_CAMPER_SHANE
#define TRAINER_CAMPER_ETHAN                     144
#define TRAINER_POKEMANIAC_STEVE_2                 TRAINER_CAMPER_ETHAN
#define TRAINER_CAMPER_RICKY                     145
#define TRAINER_POKEMANIAC_WINSTON_2               TRAINER_CAMPER_RICKY
#define TRAINER_CAMPER_JEFF                      146
#define TRAINER_GENTLEMAN_ARTHUR_2                 TRAINER_CAMPER_JEFF
#define TRAINER_CAMPER_MILO                      147
#define TRAINER_GENTLEMAN_THOMAS_2                 TRAINER_CAMPER_MILO
#define TRAINER_CAMPER_CHRIS                     148
#define TRAINER_FISHERMAN_DALE_2                   TRAINER_CAMPER_CHRIS
#define TRAINER_CAMPER_DREW                      149
#define TRAINER_GENTLEMAN_BROOKS_2                 TRAINER_CAMPER_DREW
#define TRAINER_PICNICKER_DIANA                  150
#define TRAINER_PICNICKER_NANCY                  151
#define TRAINER_GENTLEMAN_LAMAR_2                  TRAINER_PICNICKER_NANCY
#define TRAINER_CAMPER_ISAAC               152
#define TRAINER_FISHERMAN_BARNY_2                  TRAINER_CAMPER_ISAAC
#define TRAINER_CAMPER_KYLE                 153
#define TRAINER_SAILOR_PHILLIP_2                   TRAINER_CAMPER_KYLE
#define TRAINER_PICNICKER_ALICIA                 154
#define TRAINER_SAILOR_HUEY_2                      TRAINER_PICNICKER_ALICIA
#define TRAINER_PICNICKER_CAITLIN                155
#define TRAINER_SAILOR_DYLAN_2                     TRAINER_PICNICKER_CAITLIN
#define TRAINER_PICNICKER_HEIDI                  156
#define TRAINER_SAILOR_DUNCAN_2                    TRAINER_PICNICKER_HEIDI
#define TRAINER_PICNICKER_CAROL                  157
#define TRAINER_SAILOR_LEONARD_2                   TRAINER_PICNICKER_CAROL
#define TRAINER_PICNICKER_SOFIA                  158
#define TRAINER_PICNICKER_MARTHA                 159
#define TRAINER_TUBER_TINA                   160
#define TRAINER_CAMPER_HUNTER                 161
#define TRAINER_SAILOR_TREVOR_2                    TRAINER_CAMPER_HUNTER
#define TRAINER_POKEMANIAC_MARK                  162
#define TRAINER_SAILOR_EDMOND_2                    TRAINER_POKEMANIAC_MARK
#define TRAINER_POKEMANIAC_HERMAN                163
#define TRAINER_BLACK_BELT_HITOSHI_2               TRAINER_POKEMANIAC_HERMAN
#define TRAINER_POKEMANIAC_COOPER                164
#define TRAINER_POKEMANIAC_STEVE                 165
#define TRAINER_POKEMANIAC_WINSTON               166
#define TRAINER_POKEMANIAC_DAWSON                167
#define TRAINER_POKEMANIAC_ASHTON                168
#define TRAINER_SUPER_NERD_JOVAN                 169
#define TRAINER_SUPER_NERD_MIGUEL                170
#define TRAINER_PICNICKER_DIANA_2 TRAINER_SUPER_NERD_MIGUEL
#define TRAINER_SUPER_NERD_AIDAN                 171
#define TRAINER_BLACK_BELT_HIDEKI_2                TRAINER_SUPER_NERD_AIDAN
#define TRAINER_SUPER_NERD_GLENN                 172
#define TRAINER_BLACK_BELT_AARON_2                 TRAINER_SUPER_NERD_GLENN
#define TRAINER_SUPER_NERD_LESLIE                173
#define TRAINER_BLACK_BELT_MIKE_2                  TRAINER_SUPER_NERD_LESLIE
#define TRAINER_SUPER_NERD_MARVIN                174
#define TRAINER_LASS_ANN_2 TRAINER_SUPER_NERD_MARVIN
#define TRAINER_SUPER_NERD_ELLIOT                175
#define TRAINER_LASS_DAWN_2 TRAINER_SUPER_NERD_ELLIOT
#define TRAINER_SUPER_NERD_VICTOR                176
#define TRAINER_YOUNGSTER_JOHNSON_2 TRAINER_SUPER_NERD_VICTOR
#define TRAINER_SUPER_NERD_ERIK                  177
#define TRAINER_SUPER_NERD_AVERY                 178
#define TRAINER_SUPER_NERD_DEREK                 179
#define TRAINER_SUPER_NERD_ZAC                   180
#define TRAINER_HIKER_MARCOS                     181
#define TRAINER_HIKER_FRANKLIN                   182
#define TRAINER_BLACK_BELT_KOICHI_2                TRAINER_HIKER_FRANKLIN
#define TRAINER_HIKER_NOB                        183
#define TRAINER_SCIENTIST_TRAVIS_2                 TRAINER_HIKER_NOB
#define TRAINER_HIKER_WAYNE                      184
#define TRAINER_TEAM_ROCKET_GRUNT_39_2             TRAINER_HIKER_WAYNE
#define TRAINER_HIKER_ALAN                       185
#define TRAINER_TEAM_ROCKET_GRUNT_40_2             TRAINER_HIKER_ALAN
#define TRAINER_HIKER_BRICE                      186
#define TRAINER_TEAM_ROCKET_GRUNT_41_2             TRAINER_HIKER_BRICE
#define TRAINER_HIKER_CLARK                      187
#define TRAINER_TEAM_ROCKET_GRUNT_24_2             TRAINER_HIKER_CLARK
#define TRAINER_HIKER_TRENT                      188
#define TRAINER_SCIENTIST_JERRY_2                  TRAINER_HIKER_TRENT
#define TRAINER_HIKER_DUDLEY                     189
#define TRAINER_HIKER_ALLEN                      190
#define TRAINER_HIKER_ERIC                       191
#define TRAINER_HIKER_LENNY                      192
#define TRAINER_HIKER_OLIVER                     193
#define TRAINER_HIKER_LUCAS                      194
#define TRAINER_BIKER_JARED                      195
#define TRAINER_TEAM_ROCKET_GRUNT_23_2             TRAINER_BIKER_JARED
#define TRAINER_BIKER_MALIK                      196
#define TRAINER_SCIENTIST_CONNOR_2                 TRAINER_BIKER_MALIK
#define TRAINER_BIKER_ERNEST                     197
#define TRAINER_TEAM_ROCKET_GRUNT_25_2             TRAINER_BIKER_ERNEST
#define TRAINER_BIKER_ALEX                       198
#define TRAINER_SCIENTIST_JOSE_2                   TRAINER_BIKER_ALEX
#define TRAINER_BIKER_LAO                        199
#define TRAINER_TEAM_ROCKET_GRUNT_27_2             TRAINER_BIKER_LAO
#define TRAINER_BIKER_REX                        200
#define TRAINER_YOUNGSTER_CORDELL_2 TRAINER_BIKER_REX
#define TRAINER_TEAM_ROCKET_GRUNT_26_2             TRAINER_YOUNGSTER_CORDELL_2
#define TRAINER_BIKER_HIDEO                      201
#define TRAINER_SCIENTIST_RODNEY_2                 TRAINER_BIKER_HIDEO
#define TRAINER_BIKER_RUBEN                      202
#define TRAINER_TEAM_ROCKET_GRUNT_29_2             TRAINER_BIKER_RUBEN
#define TRAINER_BIKER_BILLY                      203
#define TRAINER_JUGGLER_DALTON_2                   TRAINER_BIKER_BILLY
#define TRAINER_BIKER_NIKOLAS                    204
#define TRAINER_SCIENTIST_BEAU_2                   TRAINER_BIKER_NIKOLAS
#define TRAINER_BIKER_JAXON                      205
#define TRAINER_TEAM_ROCKET_GRUNT_28_2             TRAINER_BIKER_JAXON
#define TRAINER_BIKER_WILLIAM                    206
#define TRAINER_TEAM_ROCKET_GRUNT_30_2             TRAINER_BIKER_WILLIAM
#define TRAINER_BIKER_LUKAS                      207
#define TRAINER_SCIENTIST_TAYLOR_2                 TRAINER_BIKER_LUKAS
#define TRAINER_BIKER_ISAAC                      208
#define TRAINER_TEAM_ROCKET_GRUNT_31_2             TRAINER_BIKER_ISAAC
#define TRAINER_BIKER_GERALD                     209
#define TRAINER_TEAM_ROCKET_GRUNT_33_2             TRAINER_BIKER_GERALD
#define TRAINER_BURGLAR_GORDON                   210
#define TRAINER_PICNICKER_ARIANA_2 TRAINER_BURGLAR_GORDON
#define TRAINER_BURGLAR_DEXTER                   211
#define TRAINER_LASS_KAY_2 TRAINER_BURGLAR_DEXTER
#define TRAINER_BURGLAR_MALCOLM                  212
#define TRAINER_PICNICKER_LEAH_2 TRAINER_BURGLAR_MALCOLM
#define TRAINER_BURGLAR_QUINN                    213
#define TRAINER_BURGLAR_RAMON                    214
#define TRAINER_BURGLAR_DUSTY                    215
#define TRAINER_BURGLAR_ARNIE                    216
#define TRAINER_BURGLAR_ALFRED                   217
#define TRAINER_LASS_LISA_2 TRAINER_BURGLAR_ALFRED
#define TRAINER_BURGLAR_SIMON                    218
#define TRAINER_BURGLAR_LEWIS                    219
#define TRAINER_ENGINEER_BAILY                   220
#define TRAINER_ENGINEER_BRAXTON                 221
#define TRAINER_TEAM_ROCKET_GRUNT_34_2             TRAINER_ENGINEER_BRAXTON
#define TRAINER_ENGINEER_BERNIE                  222
#define TRAINER_TEAM_ROCKET_GRUNT_35_2             TRAINER_ENGINEER_BERNIE
#define TRAINER_FISHERMAN_DALE                   223
#define TRAINER_FISHERMAN_BARNY                  224
#define TRAINER_FISHERMAN_NED                    225
#define TRAINER_SCIENTIST_JOSHUA_2                 TRAINER_FISHERMAN_NED
#define TRAINER_FISHERMAN_CHIP                   226
#define TRAINER_TEAM_ROCKET_GRUNT_32_2             TRAINER_FISHERMAN_CHIP
#define TRAINER_FISHERMAN_HANK                   227
#define TRAINER_TEAM_ROCKET_GRUNT_36_2             TRAINER_FISHERMAN_HANK
#define TRAINER_FISHERMAN_ELLIOT                 228
#define TRAINER_SCIENTIST_PARKER_2                 TRAINER_FISHERMAN_ELLIOT
#define TRAINER_FISHERMAN_RONALD                 229
#define TRAINER_SCIENTIST_ED_2                     TRAINER_FISHERMAN_RONALD
#define TRAINER_FISHERMAN_CLAUDE                 230
#define TRAINER_TEAM_ROCKET_GRUNT_38_2             TRAINER_FISHERMAN_CLAUDE
#define TRAINER_FISHERMAN_WADE                   231
#define TRAINER_TEAM_ROCKET_GRUNT_37_2             TRAINER_FISHERMAN_WADE
#define TRAINER_FISHERMAN_NOLAN                  232
#define TRAINER_COOLTRAINER_ROLANDO_2              TRAINER_FISHERMAN_NOLAN
#define TRAINER_FISHERMAN_ANDREW                 233
#define TRAINER_COOLTRAINER_NAOMI_2                TRAINER_FISHERMAN_ANDREW
#define TRAINER_SWIMMER_MALE_LUIS                234
#define TRAINER_SWIMMER_MALE_RICHARD             235
#define TRAINER_POKEMANIAC_DAWSON_2                TRAINER_SWIMMER_MALE_RICHARD
#define TRAINER_SWIMMER_MALE_REECE               236
#define TRAINER_BLACK_BELT_DAISUKE_2               TRAINER_SWIMMER_MALE_REECE
#define TRAINER_SWIMMER_MALE_MATTHEW             237
#define TRAINER_JUGGLER_NELSON_2                   TRAINER_SWIMMER_MALE_MATTHEW
#define TRAINER_SWIMMER_MALE_DOUGLAS             238
#define TRAINER_TAMER_VINCENT_2                    TRAINER_SWIMMER_MALE_DOUGLAS
#define TRAINER_SWIMMER_MALE_DAVID               239
#define TRAINER_JUGGLER_GREGORY_2                  TRAINER_SWIMMER_MALE_DAVID
#define TRAINER_SWIMMER_MALE_TONY                240
#define TRAINER_COOLTRAINER_GEORGE_2               TRAINER_SWIMMER_MALE_TONY
#define TRAINER_SWIMMER_MALE_AXLE                241
#define TRAINER_COOLTRAINER_ALEXA_2                TRAINER_SWIMMER_MALE_AXLE
#define TRAINER_SWIMMER_MALE_BARRY               242
#define TRAINER_COOLTRAINER_COLBY_2                TRAINER_SWIMMER_MALE_BARRY
#define TRAINER_SWIMMER_MALE_DEAN                243
#define TRAINER_COOLTRAINER_CAROLINE_2             TRAINER_SWIMMER_MALE_DEAN
#define TRAINER_SWIMMER_MALE_DARRIN              244
#define TRAINER_COOL_COUPLE_RAY_TYRA_2             TRAINER_SWIMMER_MALE_DARRIN
#define TRAINER_SWIMMER_MALE_SPENCER             245
#define TRAINER_BLACK_BELT_TAKASHI_2               TRAINER_SWIMMER_MALE_SPENCER
#define TRAINER_SWIMMER_MALE_JACK                246
#define TRAINER_COOLTRAINER_YUJI_2                 TRAINER_SWIMMER_MALE_JACK
#define TRAINER_SWIMMER_MALE_JEROME              247
#define TRAINER_BLACK_BELT_ATSUSHI_2               TRAINER_SWIMMER_MALE_JEROME
#define TRAINER_SWIMMER_MALE_ROLAND              248
#define TRAINER_TAMER_JASON_2                      TRAINER_SWIMMER_MALE_ROLAND
#define TRAINER_CUE_BALL_KOJI                    249
#define TRAINER_TAMER_COLE_2                       TRAINER_CUE_BALL_KOJI
#define TRAINER_CUE_BALL_LUKE                    250
#define TRAINER_BLACK_BELT_KIYO_2                  TRAINER_CUE_BALL_LUKE
#define TRAINER_CUE_BALL_CAMRON                  251
#define TRAINER_COOLTRAINER_SAMUEL_2               TRAINER_CUE_BALL_CAMRON
#define TRAINER_CUE_BALL_RAUL                    252
#define TRAINER_COOLTRAINER_WARREN_2               TRAINER_CUE_BALL_RAUL
#define TRAINER_CUE_BALL_ISAIAH                  253
#define TRAINER_BUG_CATCHER_RICK_2                 TRAINER_CUE_BALL_ISAIAH
#define TRAINER_CUE_BALL_ZEEK                    254
#define TRAINER_BUG_CATCHER_DOUG_2                 TRAINER_CUE_BALL_ZEEK
#define TRAINER_CUE_BALL_JAMAL                   255
#define TRAINER_BUG_CATCHER_SAMMY_2                TRAINER_CUE_BALL_JAMAL
#define TRAINER_CUE_BALL_COREY                   256
#define TRAINER_BUG_CATCHER_ANTHONY_2              TRAINER_CUE_BALL_COREY
#define TRAINER_CUE_BALL_CHASE                   257
#define TRAINER_CAMPER_MARCO_2 TRAINER_CUE_BALL_CHASE
#define TRAINER_BUG_CATCHER_CHARLIE_2              TRAINER_CAMPER_MARCO_2
#define TRAINER_GAMER_HUGO                       258
#define TRAINER_GAMER_JASPER                     259
#define TRAINER_GAMER_DIRK                       260
#define TRAINER_GAMER_DARIAN                     261
#define TRAINER_GAMER_STAN                       262
#define TRAINER_GAMER_RANDALL                    263
#define TRAINER_TUBER_NOAH_2 TRAINER_GAMER_RANDALL
#define TRAINER_GAMER_RICH                       264
#define TRAINER_BEAUTY_BRIDGET                   265
#define TRAINER_BEAUTY_TAMIA                     266
#define TRAINER_BEAUTY_LORI                      267
#define TRAINER_BEAUTY_LOLA                      268
#define TRAINER_BEAUTY_SHEILA                    269
#define TRAINER_SWIMMER_FEMALE_TIFFANY           270
#define TRAINER_SWIMMER_FEMALE_NORA              271
#define TRAINER_SWIMMER_FEMALE_MELISSA           272
#define TRAINER_BEAUTY_GRACE                     273
#define TRAINER_BEAUTY_OLIVIA                    274
#define TRAINER_BEAUTY_LAUREN                    275
#define TRAINER_TUBER_ALEXIS_2 TRAINER_BEAUTY_LAUREN
#define TRAINER_SWIMMER_FEMALE_ANYA              276
#define TRAINER_SWIMMER_FEMALE_ALICE             277
#define TRAINER_SWIMMER_FEMALE_CONNIE            278
#define TRAINER_SWIMMER_FEMALE_SHIRLEY           279
#define TRAINER_PSYCHIC_JOHAN                    280
#define TRAINER_PSYCHIC_TYRON                    281
#define TRAINER_PSYCHIC_CAMERON                  282
#define TRAINER_PSYCHIC_PRESTON                  283
#define TRAINER_ROCKER_RANDALL                   284
#define TRAINER_LASS_NADIA_2 TRAINER_ROCKER_RANDALL
#define TRAINER_ROCKER_LUCA                      285
#define TRAINER_JUGGLER_DALTON                   286
#define TRAINER_JUGGLER_NELSON                   287
#define TRAINER_JUGGLER_KIRK                     288
#define TRAINER_JUGGLER_SHAWN                    289
#define TRAINER_JUGGLER_GREGORY                  290
#define TRAINER_JUGGLER_EDWARD                   291
#define TRAINER_JUGGLER_KAYDEN                   292
#define TRAINER_JUGGLER_NATE                     293
#define TRAINER_TAMER_PHIL                       294
#define TRAINER_TAMER_EDGAR                      295
#define TRAINER_TAMER_JASON                      296
#define TRAINER_TAMER_COLE                       297
#define TRAINER_TAMER_VINCENT                    298
#define TRAINER_TAMER_JOHN                       299
#define TRAINER_RUNNING_TRIATHLETE_M_2 TRAINER_TAMER_JOHN
#define TRAINER_BIRD_KEEPER_SEBASTIAN            300
#define TRAINER_BIRD_KEEPER_PERRY                301
#define TRAINER_BIRD_KEEPER_ROBERT               302
#define TRAINER_BIRD_KEEPER_DONALD               303
#define TRAINER_BIRD_KEEPER_BENNY                304
#define TRAINER_BIRD_KEEPER_EDWIN                305
#define TRAINER_BIRD_KEEPER_CHESTER              306
#define TRAINER_BIRD_KEEPER_WILTON               307
#define TRAINER_BIRD_KEEPER_RAMIRO               308
#define TRAINER_BIRD_KEEPER_JACOB                309
#define TRAINER_BIRD_KEEPER_ROGER                310
#define TRAINER_BIRD_KEEPER_REED                 311
#define TRAINER_RUNNING_TRIATHLETE_F_2 TRAINER_BIRD_KEEPER_REED
#define TRAINER_BIRD_KEEPER_KEITH                312
#define TRAINER_LASS_DALIA_2 TRAINER_BIRD_KEEPER_KEITH
#define TRAINER_BIRD_KEEPER_CARTER               313
#define TRAINER_BIRD_KEEPER_MITCH                314
#define TRAINER_BIRD_KEEPER_BECK                 315
#define TRAINER_BIRD_KEEPER_MARLON               316
#define TRAINER_BLACK_BELT_KOICHI                317
#define TRAINER_BLACK_BELT_MIKE                  318
#define TRAINER_BLACK_BELT_HIDEKI                319
#define TRAINER_BLACK_BELT_AARON                 320
#define TRAINER_BLACK_BELT_HITOSHI               321
#define TRAINER_BLACK_BELT_ATSUSHI               322
#define TRAINER_BLACK_BELT_KIYO                  323
#define TRAINER_BLACK_BELT_TAKASHI               324
#define TRAINER_BLACK_BELT_DAISUKE               325
#define TRAINER_RIVAL_OAKS_LAB_SQUIRTLE          326
#define TRAINER_RIVAL_OAKS_LAB_BULBASAUR         327
#define TRAINER_RIVAL_OAKS_LAB_CHARMANDER        328
#define TRAINER_RIVAL_ROUTE22_EARLY_SQUIRTLE     329
#define TRAINER_RIVAL_ROUTE22_EARLY_BULBASAUR    330
#define TRAINER_RIVAL_ROUTE22_EARLY_CHARMANDER   331
#define TRAINER_RIVAL_CERULEAN_SQUIRTLE          332
#define TRAINER_RIVAL_CERULEAN_BULBASAUR         333
#define TRAINER_RIVAL_CERULEAN_CHARMANDER        334
#define TRAINER_SCIENTIST_TED                    335
#define TRAINER_SCIENTIST_CONNOR                 336
#define TRAINER_SCIENTIST_JERRY                  337
#define TRAINER_SCIENTIST_JOSE                   338
#define TRAINER_SCIENTIST_RODNEY                 339
#define TRAINER_SCIENTIST_BEAU                   340
#define TRAINER_SCIENTIST_TAYLOR                 341
#define TRAINER_SCIENTIST_JOSHUA                 342
#define TRAINER_SCIENTIST_PARKER                 343
#define TRAINER_SCIENTIST_ED                     344
#define TRAINER_SCIENTIST_TRAVIS                 345
#define TRAINER_SCIENTIST_BRAYDON                346
#define TRAINER_SCIENTIST_IVAN                   347
#define TRAINER_UNUSED_348                       348
#define TRAINER_BOSS_GIOVANNI_2                  349
#define TRAINER_LEADER_GIOVANNI                  350
#define TRAINER_TEAM_ROCKET_GRUNT                351
#define TRAINER_TEAM_ROCKET_GRUNT_2              352
#define TRAINER_TEAM_ROCKET_GRUNT_3              353
#define TRAINER_TEAM_ROCKET_GRUNT_4              354
#define TRAINER_UNUSED_355                       355
#define TRAINER_BUG_CATCHER_GREG_2              TRAINER_UNUSED_355
#define TRAINER_BURGLAR_LEWIS_2                    TRAINER_BUG_CATCHER_GREG_2
#define TRAINER_TEAM_ROCKET_GRUNT_6              356
#define TRAINER_UNUSED_357                       357
#define TRAINER_FISHERMAN_TOMMY_2                TRAINER_UNUSED_357
#define TRAINER_UNUSED_358                       358
#define TRAINER_FISHERMAN_TYLOR_2                TRAINER_UNUSED_358
#define TRAINER_UNUSED_359                       359
#define TRAINER_UNUSED_360                       360
#define TRAINER_UNUSED_361                       361
#define TRAINER_UNUSED_362                       362
#define TRAINER_UNUSED_363                       363
#define TRAINER_UNUSED_364                       364
#define TRAINER_UNUSED_365                       365
#define TRAINER_UNUSED_366                       366
#define TRAINER_UNUSED_367                       367
#define TRAINER_UNUSED_368                       368
#define TRAINER_TEAM_ROCKET_GRUNT_19             369
#define TRAINER_TEAM_ROCKET_GRUNT_20             370
#define TRAINER_TEAM_ROCKET_GRUNT_21             371
#define TRAINER_TEAM_ROCKET_GRUNT_22             372
#define TRAINER_TEAM_ROCKET_GRUNT_23             373
#define TRAINER_TEAM_ROCKET_GRUNT_24             374
#define TRAINER_TEAM_ROCKET_GRUNT_25             375
#define TRAINER_TEAM_ROCKET_GRUNT_26             376
#define TRAINER_TEAM_ROCKET_GRUNT_27             377
#define TRAINER_TEAM_ROCKET_GRUNT_28             378
#define TRAINER_TEAM_ROCKET_GRUNT_29             379
#define TRAINER_TEAM_ROCKET_GRUNT_30             380
#define TRAINER_TEAM_ROCKET_GRUNT_31             381
#define TRAINER_TEAM_ROCKET_GRUNT_32             382
#define TRAINER_TEAM_ROCKET_GRUNT_33             383
#define TRAINER_TEAM_ROCKET_GRUNT_34             384
#define TRAINER_TEAM_ROCKET_GRUNT_35             385
#define TRAINER_TEAM_ROCKET_GRUNT_36             386
#define TRAINER_TEAM_ROCKET_GRUNT_37             387
#define TRAINER_TEAM_ROCKET_GRUNT_38             388
#define TRAINER_TEAM_ROCKET_GRUNT_39             389
#define TRAINER_TEAM_ROCKET_GRUNT_40             390
#define TRAINER_TEAM_ROCKET_GRUNT_41             391
#define TRAINER_COOLTRAINER_SAMUEL               392
#define TRAINER_COOLTRAINER_GEORGE               393
#define TRAINER_COOLTRAINER_COLBY                394
#define TRAINER_COOLTRAINER_PAUL                 395
#define TRAINER_LASS_JOANA_2 TRAINER_COOLTRAINER_PAUL
#define TRAINER_COOLTRAINER_ROLANDO              396
#define TRAINER_COOLTRAINER_GILBERT              397
#define TRAINER_YOUNGSTER_JOSH_2 TRAINER_COOLTRAINER_GILBERT
#define TRAINER_COOLTRAINER_OWEN                 398
#define TRAINER_LASS_MIRIAM_2 TRAINER_COOLTRAINER_OWEN
#define TRAINER_COOLTRAINER_BERKE                399
#define TRAINER_PSYCHIC_JOHAN_2 TRAINER_COOLTRAINER_BERKE
#define TRAINER_COOLTRAINER_YUJI                 400
#define TRAINER_COOLTRAINER_WARREN               401
#define TRAINER_COOLTRAINER_MARY                 402
#define TRAINER_COOLTRAINER_CAROLINE             403
#define TRAINER_COOLTRAINER_ALEXA                404
#define TRAINER_COOLTRAINER_SHANNON              405
#define TRAINER_LASS_IRIS_2 TRAINER_COOLTRAINER_SHANNON
#define TRAINER_COOLTRAINER_NAOMI                406
#define TRAINER_COOLTRAINER_BROOKE               407
#define TRAINER_PSYCHIC_TYRON_2 TRAINER_COOLTRAINER_BROOKE
#define TRAINER_COOLTRAINER_AUSTINA              408
#define TRAINER_PICNICKER_SOFIA_2 TRAINER_COOLTRAINER_AUSTINA
#define TRAINER_COOLTRAINER_JULIE                409
#define TRAINER_PSYCHIC_CAMERON_2 TRAINER_COOLTRAINER_JULIE
#define TRAINER_ELITE_FOUR_LORELEI               410
#define TRAINER_ELITE_FOUR_BRUNO                 411
#define TRAINER_ELITE_FOUR_AGATHA                412
#define TRAINER_ELITE_FOUR_LANCE                 413
#define TRAINER_LEADER_BROCK_1                   414
#define TRAINER_LEADER_BROCK_2                   415
#define TRAINER_LEADER_BROCK_3                   416
#define TRAINER_LEADER_BROCK_4                   417
#define TRAINER_LEADER_BROCK_5                   418
#define TRAINER_LEADER_BROCK_6                   419
#define TRAINER_LEADER_BROCK_7                   420

#define TRAINER_LEADER_MISTY_1                   421
#define TRAINER_LEADER_MISTY                     TRAINER_LEADER_MISTY_1
#define TRAINER_LEADER_LT_SURGE_1                422
#define TRAINER_LEADER_LT_SURGE                  TRAINER_LEADER_LT_SURGE_1
#define TRAINER_LEADER_ERIKA_1                   423
#define TRAINER_LEADER_ERIKA                     TRAINER_LEADER_ERIKA_1
#define TRAINER_LEADER_KOGA_1                    424
#define TRAINER_LEADER_KOGA                      TRAINER_LEADER_KOGA_1
#define TRAINER_LEADER_BLAINE_1                  425
#define TRAINER_LEADER_BLAINE                    TRAINER_LEADER_BLAINE_1
#define TRAINER_LEADER_SABRINA_1                 426
#define TRAINER_LEADER_SABRINA                   TRAINER_LEADER_SABRINA_1
#define TRAINER_GENTLEMAN_THOMAS                 427
#define TRAINER_GENTLEMAN_ARTHUR                 428
#define TRAINER_GENTLEMAN_TUCKER                 429
#define TRAINER_GENTLEMAN_NORTON                 430
#define TRAINER_YOUNGSTER_TYLER_2 TRAINER_GENTLEMAN_NORTON
#define TRAINER_GENTLEMAN_WALTER                 431
#define TRAINER_PICNICKER_MARTHA_2 TRAINER_GENTLEMAN_WALTER
#define TRAINER_RIVAL_SS_ANNE_SQUIRTLE           432
#define TRAINER_RIVAL_SS_ANNE_BULBASAUR          433
#define TRAINER_RIVAL_SS_ANNE_CHARMANDER         434
#define TRAINER_RIVAL_POKEMON_TOWER_SQUIRTLE     435
#define TRAINER_RIVAL_POKEMON_TOWER_BULBASAUR    436
#define TRAINER_RIVAL_POKEMON_TOWER_CHARMANDER   437
#define TRAINER_RIVAL_SILPH_SQUIRTLE             438
#define TRAINER_RIVAL_SILPH_BULBASAUR            439
#define TRAINER_RIVAL_SILPH_CHARMANDER           440
#define TRAINER_RIVAL_ROUTE22_LATE_SQUIRTLE      441
#define TRAINER_RIVAL_ROUTE22_LATE_BULBASAUR     442
#define TRAINER_RIVAL_ROUTE22_LATE_CHARMANDER    443
#define TRAINER_CHAMPION_FIRST_SQUIRTLE          444
#define TRAINER_CHAMPION_FIRST_BULBASAUR         445
#define TRAINER_CHAMPION_FIRST_CHARMANDER        446
#define TRAINER_CHANNELER_PATRICIA               447
#define TRAINER_CHANNELER_CARLY                  448
#define TRAINER_CHANNELER_HOPE                   449
#define TRAINER_CHANNELER_PAULA                  450
#define TRAINER_CHANNELER_LAUREL                 451
#define TRAINER_CHANNELER_JODY                   452
#define TRAINER_CHANNELER_TAMMY                  453
#define TRAINER_CHANNELER_RUTH                   454
#define TRAINER_CHANNELER_KARINA                 455
#define TRAINER_CHANNELER_JANAE                  456
#define TRAINER_CHANNELER_ANGELICA               457
#define TRAINER_CHANNELER_EMILIA                 458
#define TRAINER_CHANNELER_JENNIFER               459
#define TRAINER_CHANNELER_1                      460
#define TRAINER_CHANNELER_2                      461
#define TRAINER_CHANNELER_3                      462
#define TRAINER_CHANNELER_4                      463
#define TRAINER_CHANNELER_5                      464
#define TRAINER_CHANNELER_6                      465
#define TRAINER_CHANNELER_7                      466
#define TRAINER_CHANNELER_8                      467
#define TRAINER_CHANNELER_AMANDA                 468
#define TRAINER_CHANNELER_STACY                  469
#define TRAINER_CHANNELER_TASHA                  470
#define TRAINER_HIKER_JEREMY                     471
#define TRAINER_PICNICKER_ALMA                   472
#define TRAINER_PICNICKER_SUSIE                  473
#define TRAINER_PICNICKER_VALERIE                474
#define TRAINER_PICNICKER_GWEN                   475
#define TRAINER_BIKER_VIRGIL                     476
#define TRAINER_CAMPER_FLINT                     477
#define TRAINER_PICNICKER_MISSY                  478
#define TRAINER_PICNICKER_IRENE                  479
#define TRAINER_PICNICKER_DANA                   480
#define TRAINER_PICNICKER_ARIANA                 481
#define TRAINER_PICNICKER_LEAH                   482
#define TRAINER_CAMPER_JUSTIN                    483
#define TRAINER_PICNICKER_YAZMIN                 484
#define TRAINER_PICNICKER_KINDRA                 485
#define TRAINER_PICNICKER_BECKY                  486
#define TRAINER_PICNICKER_CELIA                  487
#define TRAINER_GENTLEMAN_BROOKS                 488
#define TRAINER_GENTLEMAN_LAMAR                  489
#define TRAINER_TWINS_ELI_ANNE                   490
#define TRAINER_COOL_COUPLE_RAY_TYRA             491
#define TRAINER_YOUNG_COUPLE_GIA_JES             492
#define TRAINER_TWINS_KIRI_JAN                   493
#define TRAINER_CRUSH_KIN_RON_MYA                494
#define TRAINER_YOUNG_COUPLE_LEA_JED             495
#define TRAINER_SIS_AND_BRO_LIA_LUC              496
#define TRAINER_SIS_AND_BRO_LIL_IAN              497
#define TRAINER_BUG_CATCHER_3                    498
#define TRAINER_BUG_CATCHER_4                    499
#define TRAINER_BUG_CATCHER_5                    500
#define TRAINER_BUG_CATCHER_6                    501
#define TRAINER_BUG_CATCHER_7                    502
#define TRAINER_BUG_CATCHER_8                    503
#define TRAINER_YOUNGSTER_BEN_3                  504
#define TRAINER_YOUNGSTER_BEN_4                  505
#define TRAINER_YOUNGSTER_CHAD_2                 506
#define TRAINER_LASS_RELI_2                      507
#define TRAINER_LASS_RELI_3                      508
#define TRAINER_YOUNGSTER_TIMMY_2                509
#define TRAINER_YOUNGSTER_TIMMY_3                510
#define TRAINER_YOUNGSTER_TIMMY_4                511
#define TRAINER_YOUNGSTER_CHAD_3                 512
#define TRAINER_LASS_JANICE_2                    513
#define TRAINER_LASS_JANICE_3                    514
#define TRAINER_YOUNGSTER_CHAD_4                 515
#define TRAINER_HIKER_FRANKLIN_2                 516
#define TRAINER_UNUSED_517                       517
#define TRAINER_LASS_SALLY_2                    TRAINER_UNUSED_517
#define TRAINER_CHANNELER_KARINA_2                 TRAINER_LASS_SALLY_2
#define TRAINER_UNUSED_518                       518
#define TRAINER_UNUSED_519                       519
#define TRAINER_PLAYER_RED                       520
#define TRAINER_PLAYER_LEAF                      521
#define TRAINER_UNUSED_522                       522
#define TRAINER_PSYCHIC_JACLYN                   523
#define TRAINER_CRUSH_GIRL_SHARON                524
#define TRAINER_TUBER_AMIRA                      525
#define TRAINER_PKMN_BREEDER_ALIZE               526
#define TRAINER_PKMN_RANGER_NICOLAS              527
#define TRAINER_LASS_NORA_2 TRAINER_PKMN_RANGER_NICOLAS
#define TRAINER_PKMN_RANGER_MADELINE             528
#define TRAINER_BUG_CATCHER_JAMES_2 TRAINER_PKMN_RANGER_MADELINE
#define TRAINER_AROMA_LADY_NIKKI                 529
#define TRAINER_RUIN_MANIAC_STANLY               530
#define TRAINER_LADY_JACKI                       531
#define TRAINER_PAINTER_DAISY                    532
#define TRAINER_BIKER_GOON                       533
#define TRAINER_BIKER_GOON_2                     534
#define TRAINER_BIKER_GOON_3                     535
#define TRAINER_BIKER_AXEL                       536
#define TRAINER_BUG_CATCHER_KEIGO_2 TRAINER_BIKER_AXEL
#define TRAINER_BUG_CATCHER_ANTHONY              537
#define TRAINER_BUG_CATCHER_CHARLIE              538
#define TRAINER_TWINS_ELI_ANNE_2                 539
#define TRAINER_YOUNGSTER_JOHNSON                540
#define TRAINER_BIKER_RICARDO                    541
#define TRAINER_BIKER_JAREN                      542
#define TRAINER_TEAM_ROCKET_GRUNT_43             543
#define TRAINER_TEAM_ROCKET_GRUNT_44             544
#define TRAINER_TEAM_ROCKET_GRUNT_45             545
#define TRAINER_TEAM_ROCKET_GRUNT_46             546
#define TRAINER_UNUSED_547                       547
#define TRAINER_UNUSED_548                       548
#define TRAINER_UNUSED_549                       549
#define TRAINER_UNUSED_550                       550
#define TRAINER_UNUSED_551                       551
#define TRAINER_SWIMMER_FEMALE_AMARA             552
#define TRAINER_SWIMMER_FEMALE_MARIA             553
#define TRAINER_SWIMMER_FEMALE_ABIGAIL           554
#define TRAINER_SWIMMER_MALE_FINN                555
#define TRAINER_SWIMMER_MALE_GARRETT             556
#define TRAINER_FISHERMAN_TOMMY                  557
#define TRAINER_CRUSH_GIRL_TANYA                 558
#define TRAINER_BLACK_BELT_SHEA                  559
#define TRAINER_BLACK_BELT_HUGH                  560
#define TRAINER_CAMPER_BRYCE                     561
#define TRAINER_CAMPER_BLAKE                 562
#define TRAINER_CRUSH_KIN_MIK_KIA                563
#define TRAINER_AROMA_LADY_VIOLET                564
#define TRAINER_TUBER_ALEXIS                     565
#define TRAINER_TWINS_JOY_MEG                    566
#define TRAINER_SWIMMER_FEMALE_TISHA             567
#define TRAINER_PAINTER_CELINA                   568
#define TRAINER_PAINTER_RAYNA                    569
#define TRAINER_LADY_GILLIAN                     570
#define TRAINER_YOUNGSTER_DESTIN                 571
#define TRAINER_SWIMMER_MALE_TOBY                572
#define TRAINER_TEAM_ROCKET_GRUNT_49             573
#define TRAINER_TEAM_ROCKET_GRUNT_50             574
#define TRAINER_TEAM_ROCKET_GRUNT_51             575
#define TRAINER_BIRD_KEEPER_MILO                 576
#define TRAINER_BIRD_KEEPER_CHAZ                 577
#define TRAINER_BIRD_KEEPER_HAROLD               578
#define TRAINER_FISHERMAN_TYLOR                  579
#define TRAINER_SWIMMER_MALE_MYMO                580
#define TRAINER_SWIMMER_FEMALE_NICOLE            581
#define TRAINER_SIS_AND_BRO_AVA_GEB              582
#define TRAINER_AROMA_LADY_ROSE                  583
#define TRAINER_SWIMMER_MALE_SAMIR               584
#define TRAINER_SWIMMER_FEMALE_DENISE            585
#define TRAINER_TWINS_MIU_MIA                    586
#define TRAINER_HIKER_EARL                       587
#define TRAINER_RUIN_MANIAC_FOSTER               588
#define TRAINER_RUIN_MANIAC_LARRY                589
#define TRAINER_HIKER_DARYL                      590
#define TRAINER_BUG_CATCHER_ELIJAH_2 TRAINER_HIKER_DARYL
#define TRAINER_POKEMANIAC_HECTOR                591
#define TRAINER_GAMER_HUGO_2 TRAINER_POKEMANIAC_HECTOR
#define TRAINER_PSYCHIC_DARIO                    592
#define TRAINER_PSYCHIC_RODETTE                  593
#define TRAINER_AROMA_LADY_MIAH                  594
#define TRAINER_GAMER_DIRK_2 TRAINER_AROMA_LADY_MIAH
#define TRAINER_YOUNG_COUPLE_EVE_JON             595
#define TRAINER_JUGGLER_MASON                    596
#define TRAINER_SUPER_NERD_LESLIE_2 TRAINER_JUGGLER_MASON
#define TRAINER_CRUSH_GIRL_CYNDY                 597
#define TRAINER_CRUSH_GIRL_JOCELYN               598
#define TRAINER_TAMER_EVAN                       599
#define TRAINER_POKEMANIAC_MARK_2                600
#define TRAINER_PKMN_RANGER_LOGAN                601
#define TRAINER_PKMN_RANGER_JACKSON              602
#define TRAINER_PKMN_RANGER_BETH                 603
#define TRAINER_PKMN_RANGER_KATELYN              604
#define TRAINER_COOLTRAINER_LEROY                605
#define TRAINER_COOLTRAINER_MICHELLE             606
#define TRAINER_COOL_COUPLE_LEX_NYA              607
#define TRAINER_RUIN_MANIAC_BRANDON              608
#define TRAINER_RUIN_MANIAC_BENJAMIN             609
#define TRAINER_PAINTER_EDNA                     610
#define TRAINER_GENTLEMAN_CLIFFORD               611
#define TRAINER_LADY_SELPHY                      612
#define TRAINER_RUIN_MANIAC_LAWSON               613
#define TRAINER_PSYCHIC_LAURA                    614
#define TRAINER_PKMN_BREEDER_BETHANY             615
#define TRAINER_PKMN_BREEDER_ALLISON             616
#define TRAINER_BUG_CATCHER_GARRET               617
#define TRAINER_BUG_CATCHER_JONAH                618
#define TRAINER_BUG_CATCHER_VANCE                619
#define TRAINER_LASS_NADIA                   620
#define TRAINER_YOUNGSTER_CORDELL                621
#define TRAINER_LASS_DALIA                       622
#define TRAINER_LASS_JOANA                       623
#define TRAINER_CAMPER_RILEY                     624
#define TRAINER_CAMPER_MARCO                  625
#define TRAINER_RUIN_MANIAC_LAYTON               626
#define TRAINER_CAMPER_KYLE_2               627
#define TRAINER_CAMPER_KYLE_3               628
#define TRAINER_CAMPER_KYLE_4               629
#define TRAINER_CAMPER_RICKY_2                   630
#define TRAINER_CAMPER_RICKY_3                   631
#define TRAINER_CAMPER_RICKY_4                   632
#define TRAINER_CAMPER_JEFF_2                    633
#define TRAINER_CAMPER_JEFF_3                    634
#define TRAINER_CAMPER_JEFF_4                    635
#define TRAINER_CAMPER_ISAAC_2             636
#define TRAINER_CAMPER_ISAAC_3             637
#define TRAINER_CAMPER_ISAAC_4             638
#define TRAINER_YOUNGSTER_YASU_2                 639
#define TRAINER_YOUNGSTER_YASU_3                 640
#define TRAINER_ENGINEER_BERNIE_2                641
#define TRAINER_GAMER_DARIAN_2                   642
#define TRAINER_CAMPER_CHRIS_2                   643
#define TRAINER_CAMPER_CHRIS_3                   644
#define TRAINER_CAMPER_CHRIS_4                   645
#define TRAINER_PICNICKER_ALICIA_2               646
#define TRAINER_PICNICKER_ALICIA_3               647
#define TRAINER_PICNICKER_ALICIA_4               648
#define TRAINER_HIKER_JEREMY_2                   649
#define TRAINER_POKEMANIAC_MARK_3                650
#define TRAINER_POKEMANIAC_HERMAN_2              651
#define TRAINER_POKEMANIAC_HERMAN_3              652
#define TRAINER_HIKER_TRENT_2                    653
#define TRAINER_LASS_MEGAN_2                     654
#define TRAINER_LASS_MEGAN_3                     655
#define TRAINER_SUPER_NERD_GLENN_2               656
#define TRAINER_GAMER_RICH_2                     657
#define TRAINER_BIKER_JAREN_2                    658
#define TRAINER_FISHERMAN_ELLIOT_2               659
#define TRAINER_ROCKER_LUCA_2                    660
#define TRAINER_BEAUTY_SHEILA_2                  661
#define TRAINER_BIRD_KEEPER_ROBERT_2             662
#define TRAINER_BIRD_KEEPER_ROBERT_3             663
#define TRAINER_PICNICKER_SUSIE_2                664
#define TRAINER_PICNICKER_SUSIE_3                665
#define TRAINER_PICNICKER_SUSIE_4                666
#define TRAINER_BIKER_LUKAS_2                    667
#define TRAINER_BIRD_KEEPER_BENNY_2              668
#define TRAINER_BIRD_KEEPER_BENNY_3              669
#define TRAINER_BIRD_KEEPER_MARLON_2             670
#define TRAINER_BIRD_KEEPER_MARLON_3             671
#define TRAINER_BEAUTY_GRACE_2                   672
#define TRAINER_BIRD_KEEPER_CHESTER_2            673
#define TRAINER_BIRD_KEEPER_CHESTER_3            674
#define TRAINER_PICNICKER_BECKY_2                675
#define TRAINER_PICNICKER_BECKY_3                676
#define TRAINER_PICNICKER_BECKY_4                677
#define TRAINER_CRUSH_KIN_RON_MYA_2              678
#define TRAINER_CRUSH_KIN_RON_MYA_3              679
#define TRAINER_CRUSH_KIN_RON_MYA_4              680
#define TRAINER_BIKER_RUBEN_2                    681
#define TRAINER_CUE_BALL_CAMRON_2                682
#define TRAINER_BIKER_JAXON_2                    683
#define TRAINER_CUE_BALL_ISAIAH_2                684
#define TRAINER_CUE_BALL_COREY_2                 685
#define TRAINER_BIRD_KEEPER_JACOB_2              686
#define TRAINER_BIRD_KEEPER_JACOB_3              687
#define TRAINER_SWIMMER_FEMALE_ALICE_2           688
#define TRAINER_SWIMMER_MALE_DARRIN_2            689
#define TRAINER_PICNICKER_MISSY_2                690
#define TRAINER_PICNICKER_MISSY_3                691
#define TRAINER_FISHERMAN_WADE_2                 692
#define TRAINER_SWIMMER_MALE_JACK_2              693
#define TRAINER_SIS_AND_BRO_LIL_IAN_2            694
#define TRAINER_SIS_AND_BRO_LIL_IAN_3            695
#define TRAINER_SWIMMER_MALE_FINN_2              696
#define TRAINER_CRUSH_GIRL_SHARON_2              697
#define TRAINER_CRUSH_GIRL_SHARON_3              698
#define TRAINER_CRUSH_GIRL_TANYA_2               699
#define TRAINER_CRUSH_GIRL_TANYA_3               700
#define TRAINER_BLACK_BELT_SHEA_2                701
#define TRAINER_BLACK_BELT_SHEA_3                702
#define TRAINER_BLACK_BELT_HUGH_2                703
#define TRAINER_BLACK_BELT_HUGH_3                704
#define TRAINER_CRUSH_KIN_MIK_KIA_2              705
#define TRAINER_CRUSH_KIN_MIK_KIA_3              706
#define TRAINER_TUBER_AMIRA_2                    707
#define TRAINER_TWINS_JOY_MEG_2                  708
#define TRAINER_PAINTER_RAYNA_2                  709
#define TRAINER_YOUNGSTER_DESTIN_2               710
#define TRAINER_PKMN_BREEDER_ALIZE_2             711
#define TRAINER_YOUNG_COUPLE_GIA_JES_2           712
#define TRAINER_YOUNG_COUPLE_GIA_JES_3           713
#define TRAINER_BIRD_KEEPER_MILO_2               714
#define TRAINER_BIRD_KEEPER_CHAZ_2               715
#define TRAINER_BIRD_KEEPER_HAROLD_2             716
#define TRAINER_SWIMMER_FEMALE_NICOLE_2          717
#define TRAINER_PSYCHIC_JACLYN_2                 718
#define TRAINER_SWIMMER_MALE_SAMIR_2             719
#define TRAINER_HIKER_EARL_2                     720
#define TRAINER_RUIN_MANIAC_LARRY_2              721
#define TRAINER_BIKER_RICARDO_2 TRAINER_RUIN_MANIAC_LARRY_2
#define TRAINER_POKEMANIAC_HECTOR_2              722
#define TRAINER_PSYCHIC_DARIO_2                  723
#define TRAINER_PSYCHIC_RODETTE_2                724
#define TRAINER_JUGGLER_MASON_2                  725
#define TRAINER_PKMN_RANGER_NICOLAS_2            726
#define TRAINER_BIKER_HIDEO_2 TRAINER_PKMN_RANGER_NICOLAS_2
#define TRAINER_PKMN_RANGER_MADELINE_2           727
#define TRAINER_HIKER_CLARK_2 TRAINER_PKMN_RANGER_MADELINE_2
#define TRAINER_CRUSH_GIRL_CYNDY_2               728
#define TRAINER_TAMER_EVAN_2                     729
#define TRAINER_PKMN_RANGER_JACKSON_2            730
#define TRAINER_PKMN_RANGER_KATELYN_2            731
#define TRAINER_COOLTRAINER_LEROY_2              732
#define TRAINER_COOLTRAINER_MICHELLE_2           733
#define TRAINER_COOL_COUPLE_LEX_NYA_2            734
#define TRAINER_BUG_CATCHER_COLTON_2             735
#define TRAINER_BUG_CATCHER_COLTON_3             736
#define TRAINER_BUG_CATCHER_COLTON_4             737
#define TRAINER_SWIMMER_MALE_MATTHEW_2           738
#define TRAINER_SWIMMER_MALE_TONY_2              739
#define TRAINER_SWIMMER_FEMALE_MELISSA_2         740
#define TRAINER_ELITE_FOUR_LORELEI_2             741
#define TRAINER_ELITE_FOUR_BRUNO_2               742
#define TRAINER_ELITE_FOUR_AGATHA_2              743
#define TRAINER_ELITE_FOUR_LANCE_2               744
#define TRAINER_CHAMPION_REMATCH_SQUIRTLE        745
#define TRAINER_CHAMPION_REMATCH_BULBASAUR       746
#define TRAINER_CHAMPION_REMATCH_CHARMANDER      747
#define TRAINER_CUE_BALL_PAXTON                  748
#define TRAINER_LEADER_MISTY_2                   749
#define TRAINER_LEADER_MISTY_3                   750
#define TRAINER_LEADER_MISTY_4                   751
#define TRAINER_LEADER_MISTY_5                   752
#define TRAINER_LEADER_MISTY_6                   753
#define TRAINER_LEADER_MISTY_7                   754
#define TRAINER_ROCKET_ADMIN_PETREL              755
#define TRAINER_ROCKET_ADMIN_ARCHER              756
#define TRAINER_ROCKET_ADMIN_ARIANA              757
#define TRAINER_ROCKET_ADMIN_PROTON              758
#define TRAINER_LEADER_ERIKA_2                   759
#define TRAINER_LEADER_ERIKA_3                   760
#define TRAINER_LEADER_ERIKA_4                   761
#define TRAINER_LEADER_ERIKA_5                   762
#define TRAINER_LEADER_ERIKA_6                   763
#define TRAINER_LEADER_ERIKA_7                   764
#define TRAINER_TUBER_NOAH                       765

#define TRAINER_LEADER_LT_SURGE_2                TRAINER_CHANNELER_1
#define TRAINER_LEADER_LT_SURGE_3                TRAINER_CHANNELER_2
#define TRAINER_LEADER_LT_SURGE_4                TRAINER_CHANNELER_3
#define TRAINER_LEADER_LT_SURGE_5                TRAINER_CHANNELER_4
#define TRAINER_LEADER_LT_SURGE_6                TRAINER_CHANNELER_5
#define TRAINER_LEADER_LT_SURGE_7                TRAINER_CHANNELER_6
#define TRAINER_LEADER_KOGA_2                    TRAINER_CHANNELER_7
#define TRAINER_LEADER_KOGA_3                    TRAINER_CHANNELER_8
#define TRAINER_LEADER_KOGA_4                    TRAINER_BUG_CATCHER_3
#define TRAINER_LEADER_KOGA_5                    TRAINER_BUG_CATCHER_4
#define TRAINER_LEADER_KOGA_6                    TRAINER_BUG_CATCHER_5
#define TRAINER_LEADER_KOGA_7                    TRAINER_BUG_CATCHER_6
#define TRAINER_LEADER_BLAINE_2                  TRAINER_BUG_CATCHER_7
#define TRAINER_LEADER_BLAINE_3                  TRAINER_BUG_CATCHER_8
#define TRAINER_LEADER_BLAINE_4                  TRAINER_UNUSED_522
#define TRAINER_LEADER_BLAINE_5                  TRAINER_UNUSED_547
#define TRAINER_LEADER_BLAINE_6                  TRAINER_UNUSED_548
#define TRAINER_LEADER_BLAINE_7                  TRAINER_UNUSED_549
#define TRAINER_LEADER_SABRINA_2                 TRAINER_UNUSED_550
#define TRAINER_LEADER_SABRINA_3                 TRAINER_UNUSED_551
#define TRAINER_LEADER_SABRINA_4                 TRAINER_PSYCHIC_DARIO
#define TRAINER_LEADER_SABRINA_5                 TRAINER_PSYCHIC_RODETTE
#define TRAINER_LEADER_SABRINA_6                 TRAINER_PSYCHIC_DARIO_2
#define TRAINER_LEADER_SABRINA_7                 TRAINER_PSYCHIC_RODETTE_2

// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is 
//       only space for 25 additional trainers before trainer flag space overflows.
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define NUM_TRAINERS                             766
#define MAX_TRAINERS_COUNT                       774

#endif  // GUARD_CONSTANTS_OPPONENTS_H
