#ifndef GUARD_CONSTANTS_SEAGALLOP_H
#define GUARD_CONSTANTS_SEAGALLOP_H

#define SEAGALLOP_ROUTE21_NORTH            0
#define SEAGALLOP_ROUTE21_SOUTH            1
#define SEAGALLOP_SEAFOAM_ISLANDS          2
#define SEAGALLOP_ROUTE19_FUCHSIA_SHORE    3

#endif //GUARD_CONSTANTS_SEAGALLOP_H
