CinnabarIsland_PokemonLab_ResearchRoom_Text_MoltresRenewingEnergy::
    .string "Our lab studies how fire can\n"
    .string "restore as well as consume.\p"
    .string "There are reports of MOLTRES\n"
    .string "stirring life back into scorched\l"
    .string "volcanic earth.$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_LegendaryBirdEmail::
    .string "There's an e-mail message.\p"
    .string "… … …\p"
    .string "There are three legendary bird\n"
    .string "POKéMON.\p"
    .string "They are ARTICUNO, ZAPDOS, and\n"
    .string "MOLTRES.\p"
    .string "Their whereabouts are unknown.\p"
    .string "We plan to explore the cavern\n"
    .string "close to CERULEAN.\p"
    .string "From: POKéMON RESEARCH TEAM…$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_AnAmberPipe::
    .string "An amber pipe!$"
