RocketLeague_Lobby_Text_ExplainEntry::
    .string "ROCKET LEAGUE uses a single\n"
    .string "battle format.\p"
    .string "You will face TEAM ROCKET\n"
    .string "members and win COINS.\p"
    .string "Win four consecutive matches,\n"
    .string "and you'll face the champion\l"
    .string "of the league, GIOVANNI.\p"
    .string "Would you like to enter?$"

RocketLeague_Lobby_Text_WonderWhatKindsOfTrainers::
    .string "I'm here to see how good I am.\p"
    .string "I wonder what kinds of TRAINERS\n"
    .string "are waiting for me?\p"
    .string "It's nerve-racking!$"

RocketLeague_Lobby_Text_StairsTougherThanAnyBattle::
    .string "Gasp, gasp…\n"
    .string "Gasp…\p"
    .string "Never mind battling! These stairs…\n"
    .string "They're tougher than any battle…$"

RocketLeague_Lobby_Text_PrizeBoardIntro::
    .string "ROCKET LEAGUE PRIZE BOARD\p"
    .string "Standard prize multiplier:\n"
    .string "x1$"

RocketLeague_Lobby_Text_BetForTierOne::
    .string "Bet 250 COINS to raise your\n"
    .string "next arena prize to x1.5?$"

RocketLeague_Lobby_Text_BetForTierTwo::
    .string "Bet 250 COINS to raise your\n"
    .string "next arena prize to x2?$"

RocketLeague_Lobby_Text_BetForTierThree::
    .string "Bet 250 COINS to raise your\n"
    .string "next arena prize to x3?$"

RocketLeague_Lobby_Text_PrizeTierOneSet::
    .string "Your next arena prize multiplier\n"
    .string "is x1.5.$"

RocketLeague_Lobby_Text_PrizeTierTwoSet::
    .string "Your next arena prize multiplier\n"
    .string "is x2.$"

RocketLeague_Lobby_Text_PrizeTierThreeSet::
    .string "Your next arena prize multiplier\n"
    .string "is x3.$"

RocketLeague_Lobby_Text_PrizeBoardMax::
    .string "Your next arena prize multiplier\n"
    .string "is already x3.$"

RocketLeague_Lobby_Text_NotEnoughCoinsForBet::
    .string "You don't have enough COINS\n"
    .string "to place that bet.$"
