@ All Rocket League text (Lobby and Roof) is interleaved here

RocketLeague_Lobby_Text_WelcomeToRocketLeague::
    .string "Hello!\p"
    .string "Welcome to ROCKET LEAGUE where\n"
    .string "TRAINERS gather from all over!$"

RocketLeague_Lobby_Text_TrainersUpToFloorNum::
    .string "TRAINERS from all over the world\n"
    .string "gather here to battle.\p"
    .string "Let me see…\p"
    .string "Right now, there are TRAINERS only\n"
    .string "up to Floor {STR_VAR_1}.$"

RocketLeague_Lobby_Text_TrainersUpEighthFloor::
    .string "TRAINERS are awaiting your\n"
    .string "challenge up to the eighth floor.$"

RocketLeague_Lobby_Text_LikeToChallengeTrainers::
    .string "Would you like to challenge the\n"
    .string "waiting TRAINERS?$"

RocketLeague_Lobby_Text_StartClockGetSetGo::
    .string "Okay, I'll get the clock started,\n"
    .string "so give it everything you have.\p"
    .string "On your marks…\p"
    .string "Get set…\p"
    .string "Go!$"

RocketLeague_Lobby_Text_PleaseVisitUsAgain::
    .string "Please do visit us again!$"

RocketLeague_Lobby_Text_TooBadComeBackTryAgain::
    .string "That was too bad.\p"
    .string "I think you put in a tremendous\n"
    .string "effort in your battling.\p"
    .string "Please come back and try again!$"

RocketLeague_Lobby_Text_GiveItYourBest::
    .string "I hope you give it your best.$"

RocketLeague_Lobby_Text_ExplainEntry::
    .string "ROCKET LEAGUE uses a single\n"
    .string "battle format.\p"
    .string "You will face TEAM ROCKET\n"
    .string "members and win COINS.\p"
    .string "Win four consecutive matches,\n"
    .string "and you'll face the champion\l"
    .string "of the league, GIOVANNI.\p"
    .string "Would you like to enter?$"

RocketLeague_Lobby_Text_MoveCounterHereWhenTrainersSwitch::
    .string "When the TRAINERS switch places,\n"
    .string "the movement can be hectic.\p"
    .string "To avoid the stampede, we moved\n"
    .string "the reception counter here.\p"
    .string "I'm sorry for the inconvenience.$"

TrainerTower_Roof_Text_ImOwnerBattledPerfectly::
    .string "Hello…\p"
    .string "I am the owner of this TOWER…\p"
    .string "How the sky soars above this\n"
    .string "rooftop…\p"
    .string "The caress of the winds up here…\p"
    .string "It's all so perfect…\p"
    .string "The way you battled…\n"
    .string "It, too, was perfection…$"

TrainerTower_Roof_Text_ThisIsForYou::
    .string "This is for you…$"

TrainerTower_Roof_Text_DoneItInRecordTime::
    .string "Oh!\n"
    .string "Stupendous!\p"
    .string "It's marvelous how you've come up\n"
    .string "here so quickly.\p"
    .string "The fact is, you've done it in\n"
    .string "record time…\p"
    .string "I'll have your record posted at\n"
    .string "the reception counter.$"

TrainerTower_Roof_Text_TookSweetTimeGettingHere::
    .string "You seem to have taken your sweet\n"
    .string "time getting here…$"

TrainerTower_Roof_Text_IdLikeToSeeBetterTime::
    .string "What I would like to see is a\n"
    .string "better time out of you…\p"
    .string "I'm counting on you.\p"
    .string "Until then, farewell…$"

TrainerTower_Text_XMinYZSec::
    .string "{STR_VAR_1} min. {STR_VAR_2}.{STR_VAR_3} sec.$"

RocketLeague_Lobby_Text_HereAreTheResults::
    .string "せいせきひょうです$"

RocketLeague_Lobby_Text_NeedTwoMonsForDouble::
    .string "This is a two-on-two battle.\p"
    .string "You may not battle unless you have\n"
    .string "at least two POKéMON.$"

RocketLeague_Lobby_Text_ExplainRocketLeague::
    .string "Here at ROCKET LEAGUE, there is an\n"
    .string "event called TIME ATTACK.\p"
    .string "You will be timed on how quickly\n"
    .string "you can get from the reception\l"
    .string "counter to the OWNER on the roof.\p"
    .string "The best times will be recorded on\n"
    .string "the Time Board.\p"
    .string "Try competing with friends to see\n"
    .string "who can beat it the fastest.\p"
    .string "You will not earn any EXP. Points\n"
    .string "or money by beating TRAINERS here.$"

RocketLeague_Lobby_Text_ThanksForCompeting::
    .string "Thank you for competing!$"

RocketLeague_Lobby_Text_WonderWhatKindsOfTrainers::
    .string "I'm here to see how good I am.\p"
    .string "I wonder what kinds of TRAINERS\n"
    .string "are waiting for me?\p"
    .string "It's nerve-racking!$"

RocketLeague_Lobby_Text_StairsTougherThanAnyBattle::
    .string "Gasp, gasp…\n"
    .string "Gasp…\p"
    .string "Never mind battling! These stairs…\n"
    .string "They're tougher than any battle…$"

RocketLeague_Lobby_Text_PrizeBoardIntro::
    .string "ROCKET LEAGUE PRIZE BOARD\p"
    .string "Standard prize multiplier:\n"
    .string "x1$"

RocketLeague_Lobby_Text_BetForTierOne::
    .string "Bet 250 COINS to raise your\n"
    .string "next arena prize to x1.5?$"

RocketLeague_Lobby_Text_BetForTierTwo::
    .string "Bet 250 COINS to raise your\n"
    .string "next arena prize to x2?$"

RocketLeague_Lobby_Text_BetForTierThree::
    .string "Bet 250 COINS to raise your\n"
    .string "next arena prize to x3?$"

RocketLeague_Lobby_Text_PrizeTierOneSet::
    .string "Your next arena prize multiplier\n"
    .string "is x1.5.$"

RocketLeague_Lobby_Text_PrizeTierTwoSet::
    .string "Your next arena prize multiplier\n"
    .string "is x2.$"

RocketLeague_Lobby_Text_PrizeTierThreeSet::
    .string "Your next arena prize multiplier\n"
    .string "is x3.$"

RocketLeague_Lobby_Text_PrizeBoardMax::
    .string "Your next arena prize multiplier\n"
    .string "is already x3.$"

RocketLeague_Lobby_Text_NotEnoughCoinsForBet::
    .string "You don't have enough COINS\n"
    .string "to place that bet.$"
