DiglettsCave_Southside_B1F_Text_LtSurgeTeachVoltTackle::
    .string "Hey, kid!\p"
    .string "I come to DIGLETT'S CAVE\n"
    .string "regularly to train.\p"
    .string "Down here, I can go all out!\p"
    .string "The powerful electric blasts from\n"
    .string "my POKéMON are contained by the\l"
    .string "cave walls.\p"
    .string "While training here, I developed\n"
    .string "an ELECTRIC-type move.\p"
    .string "Want me to teach it?\p"
    .string "You'll need a POKéMON that can\n"
    .string "learn it.$"

DiglettsCave_Southside_B1F_Text_LtSurgeChoosePokemon::
    .string "All right, kid!\n"
    .string "Choose the POKéMON to train.$"

DiglettsCave_Southside_B1F_Text_LtSurgeComeBackWithPokemon::
    .string "No problem, kid!\p"
    .string "Come back with a POKéMON that can\n"
    .string "handle that kind of voltage.$"

DiglettsCave_Southside_B1F_Text_LtSurgeTaughtVoltTackle::
    .string "That's VOLT TACKLE!\p"
    .string "It's reckless, high-voltage power\n"
    .string "packed into a full-body charge.\p"
    .string "Heh!\n"
    .string "I like you, kid.\p"
    .string "You've got the nerve to handle\n"
    .string "real voltage.\p"
    .string "I'll meet you back at VERMILION\n"
    .string "GYM.\p"
    .string "I want a battle with you!$"
