Text_ObtainedTheX::
	.string "Obtained the {STR_VAR_2}!$"

Text_BagIsFull::
	.string "The BAG is full…$"

Text_PutItemAway::
	.string "{PLAYER} put the {STR_VAR_2}\n"
	.string "in the {STR_VAR_3}.$"

Text_FoundOneItem::
	.string "{PLAYER} found one {STR_VAR_2}!$"

Text_TooBadBagFull::
	.string "Too bad!\n"
	.string "The BAG is full…$"

Text_FoundXCoins::
	.string "{PLAYER} found\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

Text_PutCoinsAway::
	.string "{PLAYER} put the COINS away in\n"
	.string "the COIN POUCH.$"

Text_CoinPouchIsFull::
	.string "Too bad!\n"
	.string "The COIN POUCH is full…$"

Text_FoundXItems::
	.string "{PLAYER} found\n"
	.string "{STR_VAR_1} {STR_VAR_2}(s)!$"

Text_ObtainedTheDecor::
	.string "Obtained the {STR_VAR_2}!$"

Text_NoRoomForAnotherDecor::
	.string "Too bad! There's no room left for\n"
	.string "another {STR_VAR_2}…$"

Text_DecorTransferredToPC::
	.string "The {STR_VAR_2} was transferred\n"
	.string "to the PC.$"
