CeladonCity_GameCorner_Text_TryPokemonPrinter::
	.string "It's a POKéMON PRINTER!\p"
	.string "It can put a print of your POKéMON\n"
	.string "on the back of your TRAINER CARD.\p"
	.string "It costs only ¥50.\n"
	.string "Would you like to try it?$"

CeladonCity_GameCorner_Text_DontHaveEnoughMoney::
	.string "You don't have enough money.$"

CeladonCity_GameCorner_Text_ChoosePrintType::
	.string "Please choose the print type.$"

CeladonCity_GameCorner_Text_BigSmileForPhoto::
	.string "A big smile for the photo, please!\n"
	.string "Three… Two… One…\p"
	.string "Flash!$"

CeladonCity_GameCorner_Text_PrintIsReadyCheckTrainerCard::
	.string "Your POKéMON print is ready!\n"
	.string "Check your TRAINER CARD.$"
