SevenIsland_PokemonCenter_1F_Text_EventsDependingOnConnections::
    .string "On this island, different events\n"
    .string "occur depending on connections.\p"
    .string "What are those connections?\p"
    .string "They are for you to discover on\n"
    .string "your own.$"

SevenIsland_PokemonCenter_1F_Text_DidYouRideFerryHere::
    .string "Did you ride the ferry\n"
    .string "to get here?$"

SevenIsland_PokemonCenter_1F_Text_SevaultCanyon::
    .string "SEVAULT CANYON is ahead.\p"
    .string "Take care if you're headed\n"
    .string "that way.$"
