LavenderTown_PokemonCenter_1F_Text_RestHere::
    .string "Welcome, traveler.\p"
    .string "This is a HEALING HOUSE.\n"
    .string "Would you like to rest your POKéMON?$"

LavenderTown_PokemonCenter_1F_Text_Goodbye::
    .string "May your journey be a peaceful one.$"

LavenderTown_PokemonCenter_1F_Text_TakeShortRest::
    .string "All right.\n"
    .string "Take a short rest here.$"

LavenderTown_PokemonCenter_1F_Text_Rested::
    .string "Your POKéMON look calm and\n"
    .string "rested again.$"

LavenderTown_PokemonCenter_1F_Text_RocketsDoAnythingForMoney::
    .string "TEAM ROCKET will do anything for\n"
    .string "the sake of money!\p"
    .string "There is no job too dirty, no deed\n"
    .string "too heinous, no crime too wicked!$"

LavenderTown_PokemonCenter_1F_Text_CubonesMotherKilledByRockets::
    .string "I saw CUBONE's mother trying to\n"
    .string "escape from TEAM ROCKET.\p"
    .string "She was killed trying to get away…$"

LavenderTown_PokemonCenter_1F_Text_PeoplePayForCuboneSkulls::
    .string "You know how the CUBONE species\n"
    .string "wears skulls, right?\p"
    .string "People will pay a lot for one.$"
