Route2_EastBuilding_Text_GiveTM55IfSeen10Mons::
    .string "Hi! Remember me?\n"
    .string "I'm one of PROF. OAK's AIDES.\p"
    .string "If your POKéDEX has complete data\n"
    .string "on ten species, I'm supposed to\l"
    .string "check on your progress.\p"
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Have you gathered data on at least\n"
    .string "ten kinds of POKéMON?$"

Route2_EastBuilding_Text_GreatHereYouGo::
    .string "Great! You have caught or owned\n"
    .string "{STR_VAR_3} kinds of POKéMON!\p"
    .string "Congratulations!\n"
    .string "PROF. OAK will be pleased.$"

Route2_EastBuilding_Text_ReceivedTM55FromAide::
    .string "{PLAYER} received TM55\n"
    .string "from the AIDE.$"

Route2_EastBuilding_Text_ExplainTM55::
    .string "Keep gathering POKéDEX data.\n"
    .string "PROF. OAK is counting on you.$"

Route2_EastBuilding_Text_CanGetThroughRockTunnel::
    .string "Once a POKéMON learns FLASH, you\n"
    .string "can get through ROCK TUNNEL.$"
