ViridianCity_Gym_Text_GiovanniIntro::
    .string "Fwahahaha!\n"
    .string "Welcome to my hideout!\p"
    .string "It shall be so until I can restore\n"
    .string "TEAM ROCKET to its former glory.\p"
    .string "But, you have found me again.\n"
    .string "So be it.\l"
    .string "This time, I'm not holding back!\p"
    .string "Once more, you shall face\n"
    .string "GIOVANNI, the greatest TRAINER!{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"

ViridianCity_Gym_Text_GiovanniDefeat::
    .string "Ha!\n"
    .string "That was a truly intense fight.\l"
    .string "You have won!\p"
    .string "As proof, here is the EARTHBADGE!\n"
    .string "{PAUSE_MUSIC}{PLAY_BGM}{MUS_OBTAIN_BADGE}{PAUSE 0xFE}{PAUSE 0x56}{RESUME_MUSIC}$"

ViridianCity_Gym_Text_GiovanniPostBattle::
    .string "Having lost in this fashion, \n"
    .string "I can't face my followers.\l"
    .string "I have betrayed their trust.\p"
    .string "As of today, TEAM ROCKET is\n"
    .string "finished forever!\p"
    .string "As for myself, I shall dedicate\n"
    .string "my life to training again.\p"
    .string "Let us meet again someday!\n"
    .string "Farewell!$"

ViridianCity_Gym_Text_ExplainEarthBadgeTakeThis::
    .string "The EARTHBADGE is evidence of\n"
    .string "your mastery as a TRAINER.\p"
    .string "But obedience is earned through\n"
    .string "the trust recorded in your\l"
    .string "FIELD AIDE work.\p"
    .string "With it, you can challenge the\n"
    .string "POKéMON LEAGUE.\p"
    .string "Go. Your path lies ahead.$"

ViridianCity_Gym_Text_UnusedGiovanniReward::
    .string "{PLAYER} received something\n"
    .string "from GIOVANNI.$"

ViridianCity_Gym_Text_ExplainEarthquake::
    .string "EARTHQUAKE is a powerful attack\n"
    .string "that causes a massive tremor.\p"
    .string "I made it when I ran the GYM here,\n"
    .string "far too long ago… $"

ViridianCity_Gym_Text_YouDoNotHaveSpace::
    .string "You do not have space for this!$"

ViridianCity_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "Even I don't know the VIRIDIAN\n"
    .string "LEADER's identity.\p"
    .string "But one thing's certain.\n"
    .string "This will be the toughest of all\l"
    .string "the GYM LEADERS.\p"
    .string "Also, I heard that the TRAINERS\n"
    .string "here like GROUND-type POKéMON.$"

ViridianCity_Gym_Text_GymGuyPostVictory::
    .string "Blow me away! GIOVANNI was the\n"
    .string "GYM LEADER of VIRIDIAN?$"

ViridianCity_Gym_Text_GymStatue::
    .string "VIRIDIAN POKéMON GYM\n"
    .string "LEADER: ?\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"

ViridianCity_Gym_Text_GymStatuePlayerWon::
    .string "VIRIDIAN POKéMON GYM\n"
    .string "LEADER: GIOVANNI\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"
