CeruleanCity_House2_Text_RepairsCostABundle::
    .string "Look at the state of my house!\p"
    .string "I should have fixed that old wall\n"
    .string "years ago.\p"
    .string "That repair is going to cost me a\n"
    .string "bundle, it is!$"

CeruleanCity_House2_Text_RepairWorkIsExhausting::
    .string "Repair work is exhausting.\p"
    .string "At least there's a breeze through\n"
    .string "the back wall.$"

CeruleanCity_House2_Text_WallNeedsRepairs::
    .string "The wall needs repairs.$"
