SSAnne_2F_Room2_Text_BrooksIntro::
    .string "Competing against the young keeps\n"
    .string "me youthful.$"

SSAnne_2F_Room2_Text_BrooksDefeat::
    .string "Good match!\n"
    .string "Ah, I feel young again!$"

SSAnne_2F_Room2_Text_BrooksPostBattle::
    .string "Fifteen years ago, I would\n"
    .string "have won!$"

SSAnne_2F_Room2_Text_DaleIntro::
    .string "A fine voyage calls for a fine\n"
    .string "battle, wouldn't you say?$"

SSAnne_2F_Room2_Text_DaleDefeat::
    .string "A costly lesson!$"

SSAnne_2F_Room2_Text_DalePostBattle::
    .string "The ship's party was splendid.\p"
    .string "The battles afterward have been\n"
    .string "rather lively, too.$"
