FourIsland_LoreleisHouse_Text_IfAnythingWereToHappenToIsland::
    .string "LORELEI: There's something weighing\n"
    .string "heavily on my mind.\p"
    .string "If anything were to happen on\n"
    .string "the island where I was born…\p"
    .string "I wouldn't know about it if I were\n"
    .string "in the POKéMON LEAGUE.\p"
    .string "I wonder if that would make me\n"
    .string "irresponsible to my home…$"

FourIsland_LoreleisHouse_Text_StuffedMonDollsGalore::
    .string "Stuffed POKéMON dolls galore!$"
