SSAnne_1F_Room2_Text_TylerIntro::
    .string "Father says a proper trainer\n"
    .string "accepts every challenge.$"

SSAnne_1F_Room2_Text_TylerDefeat::
    .string "Oh!\n"
    .string "That was not proper at all!$"

SSAnne_1F_Room2_Text_TylerPostBattle::
    .string "I shall have to train harder\n"
    .string "before the next voyage.$"

SSAnne_1F_Room2_Text_AnnIntro::
    .string "I collected these POKéMON\n"
    .string "from all around the world!$"

SSAnne_1F_Room2_Text_AnnDefeat::
    .string "Oh, no!\n"
    .string "I went around the world for these!$"

SSAnne_1F_Room2_Text_AnnPostBattle::
    .string "You hurt my poor POKéMON!\p"
    .string "I demand that you heal them at a\n"
    .string "POKéMON CENTER!$"

SSAnne_1F_Room2_Text_CruisingAroundWorld::
    .string "We are cruising around the world,\n"
    .string "my children and I.$"
