Text_MetronomeTeach::
    .string "Tch-tch-tch!\n"
    .string "I'll teach you a nifty move.\p"
    .string "Teach it to a POKéMON, and watch\n"
    .string "the fun unfold!\p"
    .string "It's a move called METRONOME.\n"
    .string "Does it strike your fancy?$"

Text_MetronomeDeclined::
    .string "I tell you, it's a lot of fun!$"

Text_MetronomeWhichMon::
    .string "Okay!\n"
    .string "Which POKéMON should I teach?$"

Text_MetronomeTaught::
    .string "Tch-tch-tch!\n"
    .string "That's the sound of a METRONOME.\p"
    .string "It tweaks your POKéMON's brain into\n"
    .string "using moves it doesn't even know.$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_Intro::
    .string "Hiya!\p"
    .string "I am important doctor.\n"
    .string "Yes, very much so, indeed.\p"
    .string "Here, I study rare POKéMON fossils.\n"
    .string "All the time, I study.\p"
    .string "You!\n"
    .string "Have you a fossil for me?$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoIsTooBad::
    .string "No!\n"
    .string "Is too bad!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_Cancel::
    .string "Come back when you're ready.$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_Success::
    .string "Success!\n"
    .string "Your fossil is now a living POKéMON!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_MissingFossil::
    .string "You don't have the right fragments.$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_MissingAmber::
    .string "You don't have OLD AMBER.$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ConfirmOmanyte::
    .string "OMANYTE, the cephalopod mollusk POKéMON!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ConfirmOmato::
    .string "OMATO, the cephalopod crab POKéMON!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ConfirmKabuto::
    .string "KABUTO, the horseshoe crab POKéMON!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ConfirmKabustar::
    .string "KABUSTAR, the horseshoe mollusk POKéMON!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ConfirmAerodactyl::
    .string "AERODACTYL, the fossil pterosaur POKéMON!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_FossilMonBackToLife::
    .string "You late.\n"
    .string "Where were you?\p"
    .string "Your fossil is back to life!\n"
    .string "It was {STR_VAR_1} like I think!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ReceivedMonFromDoctor::
    .string "{PLAYER} received the {STR_VAR_1}\n"
    .string "from the doctor.$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoRoomForPokemon::
    .string "ポケモン　いっぱいで　もてないね！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ThatFossilIsOfMonMakeItLiveAgain::
    .string "Oh!\n"
    .string "That is {STR_VAR_2}, it is!\p"
    .string "It is fossil of {STR_VAR_1},\n"
    .string "a POKéMON that is already extinct!\p"
    .string "My Resurrection Machine will make\n"
    .string "that POKéMON live again!$"

@ TODO: Resolve text dump error below?
CinnabarIsland_PokemonLab_ExperimentRoom_Text_HandedFossilToWeirdDoctor::
    .string "So!\n"
    .string "You hurry and give me that!\p"
    .string "{FONT_NORMAL}{PLAYER} handed over the\n"
    .string "{STR_VAR_2} to the weird doctor.$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalk::
    .string "I take a little time!\n"
    .string "You go for walk a little while!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_YouComeAgain::
    .string "Aiyah!\n"
    .string "You come again!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ProtectorTrade::
    .string "Our lab developed the PROTECTOR,\n"
    .string "a tough suit of protective gear.\p"
    .string "My RHYDON is holding one.\n"
    .string "Trading it helps that protection\l"
    .string "become part of its new body.\p"
    .string "It evolves into RHYPERIOR!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ProtectorResult::
    .string "RHYDON made our invention\n"
    .string "part of itself!\p"
    .string "Take good care of RHYPERIOR.\n"
    .string "There's more to it than armor!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ProtectorResearch::
    .string "We built the PROTECTOR here\n"
    .string "to help RHYDON grow stronger.\p"
    .string "Making the item was our work.\n"
    .string "The evolution belongs to RHYDON.$"
