SafariZone_East_Text_RestHouse::
    .string "REST HOUSE$"

SafariZone_East_Text_AreaSign::
    .string "AREA 1\n"
    .string "WEST: CENTER AREA$"

SafariZone_East_Text_GravelerTradeIntro::
	.string "These GRAVELER are from ALOLA.\n"
	.string "Trading makes them evolve!\p"
	.string "Catch one here, and we can swap\n"
	.string "our Alolan GRAVELER.\p"
	.string "You'll receive an Alolan GOLEM!$"

SafariZone_East_Text_GravelerTradeThanks::
	.string "There it is! An Alolan GOLEM!\p"
	.string "Thanks for helping my research.$"

SafariZone_East_Text_GravelerTradeDone::
	.string "How is your Alolan GOLEM?\p"
	.string "Those rocky whiskers give it\n"
	.string "quite a distinguished look!$"

SafariZone_East_Text_GravelerTradeWrongMon::
	.string "I need an Alolan GRAVELER,\n"
	.string "like the ones found here.$"
