Route18_EastEntrance_1F_Text_NeedBicycleForCyclingRoad::
    .string "You need a BICYCLE to go out on\n"
    .string "CYCLING ROAD!$"

Route18_EastEntrance_1F_Text_CyclingRoadAllUphillFromHere::
    .string "CYCLING ROAD is all uphill from\n"
    .string "here.$"

Route18_EastEntrance_1F_Text_RentBike::
    .string "No BICYCLE?\p"
    .string "You can rent one here for Routes\n"
    .string "16, 17, and 18.\p"
    .string "The rental fee is 500.\p"
    .string "Rent a BICYCLE?$"

Route18_EastEntrance_1F_Text_RentalStarted::
    .string "All set!\p"
    .string "Ride carefully, and return it\n"
    .string "when you leave the route.$"

Route18_EastEntrance_1F_Text_RentalActive::
    .string "Your rental BICYCLE is ready.\p"
    .string "It can be used on Routes 16,\n"
    .string "17, and 18.$"

Route18_EastEntrance_1F_Text_OwnBike::
    .string "You've got your own BICYCLE.\p"
    .string "You're ready for CYCLING ROAD.$"

Route18_EastEntrance_1F_Text_ExcuseMe::
    .string "Excuse me!$"

Route18_EastEntrance_1F_Text_NotEnoughMoney::
    .string "You don't have enough money.$"

Route18_EastEntrance_1F_Text_ReturnRentalBike::
    .string "Welcome back.\p"
    .string "I'll take the rental BICYCLE\n"
    .string "from here.$"
