CinnabarVolcano_1F_Text_WaterWarmsMeToCore::
    .string "Hm!\n"
    .string "Haaaaaaaaaaah!\p"
    .string "Aaaah! This is heavenly!\n"
    .string "The water warms me to my core!\p"
    .string "You should jump in, too.\p"
    .string "Go to the middle, relax, and get\n"
    .string "good and warm!$"

CinnabarVolcano_1F_Text_EnjoyBowlOfChowder::
    .string "My favorite part of bathing comes\n"
    .string "up right after this.\p"
    .string "I enjoy a bowl of chowder to\n"
    .string "warm me from the inside, too!$"

CinnabarVolcano_1F_Text_WaterExquisiteFullyRefreshed::
    .string "The water is perfectly warm.\n"
    .string "It feels exquisite…\p"
    .string "{PLAYER} and the POKéMON were\n"
    .string "fully refreshed!$"

CinnabarVolcano_1F_Text_HotSpringIsTherapeutic::
    .string "Soaking in a hot spring pool is\n"
    .string "therapeutic, people say.$"

CinnabarVolcano_1F_Text_SeeHowSmoothMySkinIs::
    .string "Have a look at my face.\n"
    .string "See how smooth my skin is?\p"
    .string "The hot spring's water keeps my\n"
    .string "skin younger than my age.$"

CinnabarVolcano_1F_Text_BrunoVisitsSpaOnOccasion::
    .string "After an honest day of training,\n"
    .string "nothing beats a relaxing soak in\l"
    .string "the hot spring pool.\p"
    .string "BRUNO, who's a senior ahead of me,\n"
    .string "visits the SPA on occasion.\p"
    .string "He comes to rehab injuries, both\n"
    .string "his own and his POKéMON's.$"

CinnabarVolcano_1F_Text_KogaLookingForLavicStone::
    .string "KOGA: Fwahahaha!\p"
    .string "You have found me at work,\n"
    .string "{PLAYER}.\p"
    .string "I seek a LAVIC STONE, quenched\n"
    .string "by the thermal waters of this\l"
    .string "volcano.\p"
    .string "Such stone can be shaped into\n"
    .string "excellent ninja tools.\p"
    .string "But even a stone born of fire\n"
    .string "needs water to become useful.\p"
    .string "So it is with people.\p"
    .string "Togetherness is what will allow\n"
    .string "us to reach the stone.\p"
    .string "I challenge you, {PLAYER}.\p"
    .string "Reach the water source with me,\n"
    .string "and prove you understand the\l"
    .string "strength of moving together!\p"
    .string "Now, follow if you can!$"
