CinnabarVolcano_3F_Text_BlairIntro::
    .string "Deep enough, even the rocks\n"
    .string "start to glow.$"

CinnabarVolcano_3F_Text_BlairDefeat::
    .string "Burned out!$"

CinnabarVolcano_3F_Text_BlairPostBattle::
    .string "Fire-types love this pressure.\p"
    .string "Down here, even burned ground\n"
    .string "feels alive again.\p"
    .string "Like the volcano keeps renewing\n"
    .string "its own energy.$"

CinnabarVolcano_3F_Text_EliasIntro::
    .string "These stones remember every\n"
    .string "eruption. I study them all!$"

CinnabarVolcano_3F_Text_EliasDefeat::
    .string "A historic defeat!$"

CinnabarVolcano_3F_Text_EliasPostBattle::
    .string "Volcanic rock tells the story\n"
    .string "of how CINNABAR was formed.$"
