Route2_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

Route2_EventScript_ItemParalyzeHeal::
	finditem ITEM_PARALYZE_HEAL
	end

ViridianForest_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

ViridianForest_EventScript_ItemAntidote::
	finditem ITEM_ANTIDOTE
	end

ViridianForest_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

MtMoon_1F_EventScript_ItemParalyzeHeal::
	finditem ITEM_PARALYZE_HEAL
	end

MtMoon_1F_EventScript_ItemSuperPotion::
	finditem ITEM_SUPER_POTION
	end

MtMoon_1F_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

MtMoon_1F_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

MtMoon_1F_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

MtMoon_1F_EventScript_ItemMoonStone::
	finditem ITEM_MOON_STONE
	end

MtMoon_B2F_EventScript_ItemStarPiece::
	finditem ITEM_STAR_PIECE
	end

MtMoon_B2F_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

Route4_EventScript_ItemAwakening::
	finditem ITEM_AWAKENING
	end

Route24_EventScript_ItemSitrusBerry::
	finditem ITEM_SITRUS_BERRY
	end

Route25_EventScript_ItemLumBerry::
	finditem ITEM_LUM_BERRY
	end

SSAnne_1F_Room2_EventScript_ItemXAttack::
	finditem ITEM_X_ATTACK
	end

SSAnne_2F_Room2_EventScript_ItemStardust::
	finditem ITEM_STARDUST
	end

SSAnne_2F_Room4_EventScript_ItemXAttack::
	finditem ITEM_X_ATTACK
	end

SSAnne_B1F_Room2_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

SSAnne_B1F_Room3_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

SSAnne_B1F_Room5_EventScript_ItemSuperPotion::
	finditem ITEM_SUPER_POTION
	end

SSAnne_Kitchen_EventScript_ItemGreatBall::
	finditem ITEM_GREAT_BALL
	end

Route9_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

PokemonTower_2F_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

PokemonTower_3F_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

PokemonTower_3F_EventScript_ItemXAccuracy::
	finditem ITEM_X_ACCURACY
	end

Route12_EventScript_ItemXAccuracy::
	finditem ITEM_X_ACCURACY
	end

Route12_EventScript_ItemIron::
	finditem ITEM_IRON
	end

Route15_EventScript_ItemSitrusBerry::
	finditem ITEM_SITRUS_BERRY
	end

SafariZone_Center_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

SafariZone_East_EventScript_ItemMaxPotion::
	finditem ITEM_MAX_POTION
	end

SafariZone_East_EventScript_ItemFullRestore::
	finditem ITEM_FULL_RESTORE
	end

SafariZone_East_EventScript_ItemLumBerry::
	finditem ITEM_LUM_BERRY
	end

SafariZone_East_EventScript_ItemLeafStone::
	finditem ITEM_LEAF_STONE
	end

SafariZone_North_EventScript_ItemProtein::
	finditem ITEM_PROTEIN
	end

SafariZone_North_EventScript_ItemMaxPotion::
	finditem ITEM_MAX_POTION
	end

SafariZone_West_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

SafariZone_West_EventScript_ItemGoldTeeth::
	finditem ITEM_GOLD_TEETH
	end

SafariZone_West_EventScript_ItemMaxPotion::
	finditem ITEM_MAX_POTION
	end

SafariZone_West_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

SilphCo_3F_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

SilphCo_4F_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

SilphCo_4F_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

SilphCo_4F_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

SilphCo_5F_EventScript_ItemProtein::
	finditem ITEM_PROTEIN
	end

SilphCo_5F_EventScript_ItemXAttack::
	finditem ITEM_X_ATTACK
	end

SilphCo_5F_EventScript_ItemCardKey::
	finditem ITEM_CARD_KEY
	end

SilphCo_6F_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

SilphCo_6F_EventScript_ItemXSpecial::
	finditem ITEM_X_SPECIAL
	end

SilphCo_7F_EventScript_ItemCalcium::
	finditem ITEM_CALCIUM
	end

SilphCo_7F_EventScript_ItemXDefend::
	finditem ITEM_X_DEFEND
	end

SilphCo_10F_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

SilphCo_10F_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

SilphCo_10F_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

PowerPlant_EventScript_ItemMaxPotion::
	finditem ITEM_MAX_POTION
	end

PowerPlant_EventScript_ItemXAccuracy::
	finditem ITEM_X_ACCURACY
	end

PowerPlant_EventScript_ItemMaxRepel::
	finditem ITEM_MAX_REPEL
	end

PowerPlant_EventScript_ItemThunderStone::
	finditem ITEM_THUNDER_STONE
	end

PowerPlant_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

PokemonMansion_1F_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

PokemonMansion_1F_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

PokemonMansion_2F_EventScript_ItemCalcium::
	finditem ITEM_CALCIUM
	end

PokemonMansion_3F_EventScript_ItemMaxPotion::
	finditem ITEM_MAX_POTION
	end

PokemonMansion_3F_EventScript_ItemIron::
	finditem ITEM_IRON
	end

PokemonMansion_B1F_EventScript_ItemMaxPotion::
	finditem ITEM_MAX_POTION
	end

PokemonMansion_B1F_EventScript_ItemFullRestore::
	finditem ITEM_FULL_RESTORE
	end

PokemonMansion_B1F_EventScript_ItemSitrusBerry::
	finditem ITEM_SITRUS_BERRY
	end

VictoryRoad_1F_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

VictoryRoad_1F_EventScript_ItemFullRestore::
	finditem ITEM_FULL_RESTORE
	end

VictoryRoad_2F_EventScript_ItemGuardSpec::
	finditem ITEM_GUARD_SPEC
	end

VictoryRoad_2F_EventScript_ItemLumBerry::
	finditem ITEM_LUM_BERRY
	end

VictoryRoad_2F_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

VictoryRoad_2F_EventScript_ItemMaxPotion::
	finditem ITEM_MAX_POTION
	end

VictoryRoad_3F_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

VictoryRoad_3F_EventScript_ItemFullRestore::
	finditem ITEM_FULL_RESTORE
	end

CeruleanCave_1F_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

CeruleanCave_1F_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

CeruleanCave_1F_EventScript_ItemFullRestore::
	finditem ITEM_FULL_RESTORE
	end

CeruleanCave_2F_EventScript_ItemFullRestore::
	finditem ITEM_FULL_RESTORE
	end

CeruleanCave_2F_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

CeruleanCave_2F_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

CeruleanCave_B1F_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

CeruleanCave_B1F_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

FuchsiaCity_WardensHouse_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

ViridianForest_EventScript_ItemPotion2::
	finditem ITEM_POTION
	end

MtMoon_B2F_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

MtMoon_B2F_EventScript_ItemAntidote::
	finditem ITEM_ANTIDOTE
	end

Route11_EventScript_ItemXDefend::
	finditem ITEM_X_DEFEND
	end

Route9_EventScript_ItemBurnHeal::
	finditem ITEM_BURN_HEAL
	end

RockTunnel_1F_EventScript_ItemRepel::
	finditem ITEM_REPEL
	end

RockTunnel_1F_EventScript_ItemPearl::
	finditem ITEM_PEARL
	end

RockTunnel_1F_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

RockTunnel_B1F_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

RockTunnel_B1F_EventScript_ItemMaxEther::
	finditem ITEM_MAX_ETHER
	end

SilphCo_8F_EventScript_ItemIron::
	finditem ITEM_IRON
	end

SilphCo_11F_EventScript_ItemZinc::
	finditem ITEM_ZINC
	end

PokemonMansion_1F_EventScript_ItemProtein::
	finditem ITEM_PROTEIN
	end

PokemonMansion_2F_EventScript_ItemZinc::
	finditem ITEM_ZINC
	end

PokemonMansion_2F_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

ViridianCity_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route11_EventScript_ItemGreatBall::
	finditem ITEM_GREAT_BALL
	end

Route11_EventScript_ItemAwakening::
	finditem ITEM_AWAKENING
	end

CeladonCity_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

SafariZone_North_EventScript_ItemQuickClaw::
	finditem ITEM_QUICK_CLAW
	end

SeafoamIslands_1F_EventScript_ItemIceHeal::
	finditem ITEM_ICE_HEAL
	end

SeafoamIslands_B1F_EventScript_ItemWaterStone::
	finditem ITEM_WATER_STONE
	end

SeafoamIslands_B1F_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

SeafoamIslands_B2F_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

SeafoamIslands_B4F_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

FuchsiaForest_EventScript_ItemMaxEther::
	finditem ITEM_MAX_ETHER
	end

FuchsiaForest_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

FuchsiaForest_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

SilphCo_4F_EventScript_ItemXSpecial::
	finditem ITEM_X_SPECIAL
	end
