CeruleanCity_House1_Text_BadgesHaveAmazingSecrets::
    .string "Only skilled TRAINERS can collect\n"
    .string "POKéMON BADGES.\p"
    .string "I see you have at least one.\p"
    .string "Those BADGES have amazing secrets,\n"
    .string "did you know?$"

CeruleanCity_House1_Text_DescribeWhichBadge::
    .string "Now then…\p"
    .string "Which of the eight BADGES should\n"
    .string "I describe?$"

CeruleanCity_House1_Text_ComeVisitAnytime::
    .string "Come visit me anytime you wish.$"

CeruleanCity_House1_Text_AttackStatFlash::
    .string "The BOULDERBADGE is proof that\n"
    .string "you defeated PEWTER GYM's LEADER.$"

CeruleanCity_House1_Text_ObeyLv30Cut::
    .string "With two BADGES, POKéMON up\n"
    .string "to Lv. 30 will obey you.\p"
    .string "That includes even outsiders you\n"
    .string "obtain in trades.\p"
    .string "POKéMON of higher levels will\n"
    .string "be unruly in battle, however.$"

CeruleanCity_House1_Text_SpeedStatFly::
    .string "The THUNDERBADGE is proof that\n"
    .string "you defeated VERMILION GYM's LEADER.$"

CeruleanCity_House1_Text_ObeyLv50Strength::
    .string "With four BADGES, POKéMON up\n"
    .string "to Lv. 50 will obey you.\p"
    .string "That includes even outsiders you\n"
    .string "obtain in trades.\p"
    .string "POKéMON of higher levels will\n"
    .string "be unruly in battle, however.\p"
    .string "It also lets you use the move\n"
    .string "STRENGTH outside of battle.$"

CeruleanCity_House1_Text_DefenseStatSurf::
    .string "The SOULBADGE is proof that\n"
    .string "you defeated FUCHSIA GYM's LEADER.$"

CeruleanCity_House1_Text_ObeyLv70RockSmash::
    .string "With six BADGES, POKéMON up\n"
    .string "to Lv. 70 will obey you.\p"
    .string "That includes even outsiders you\n"
    .string "obtain in trades.\p"
    .string "POKéMON of higher levels will\n"
    .string "be unruly in battle, however.\p"
    .string "It also lets you use the move\n"
    .string "ROCK SMASH outside of battle.$"

CeruleanCity_House1_Text_SpStatsWaterfall::
    .string "The VOLCANOBADGE is proof that\n"
    .string "you defeated CINNABAR GYM's LEADER.$"

CeruleanCity_House1_Text_AllMonsWillObeyYou::
    .string "With all eight BADGES, all\n"
    .string "POKéMON will obey you!$"
