CeruleanCity_House1_Text_BadgesHaveAmazingSecrets::
    .string "Only skilled TRAINERS can collect\n"
    .string "POKéMON BADGES.\p"
    .string "I see you have at least one.\p"
    .string "Those BADGES have amazing secrets,\n"
    .string "did you know?$"

CeruleanCity_House1_Text_DescribeWhichBadge::
    .string "Now then…\p"
    .string "Which of the eight BADGES should\n"
    .string "I describe?$"

CeruleanCity_House1_Text_ComeVisitAnytime::
    .string "Come visit me anytime you wish.$"

CeruleanCity_House1_Text_AttackStatFlash::
    .string "The BOULDERBADGE is proof that\n"
    .string "you defeated PEWTER GYM's LEADER.$"

CeruleanCity_House1_Text_ObeyLv30Cut::
    .string "BADGES are proof of skill, but\n"
    .string "obedience comes from trust.\p"
    .string "As your FIELD AIDE record grows,\n"
    .string "outsider POKéMON will better\l"
    .string "respect your commands.$"

CeruleanCity_House1_Text_SpeedStatFly::
    .string "The THUNDERBADGE is proof that\n"
    .string "you defeated VERMILION GYM's LEADER.$"

CeruleanCity_House1_Text_ObeyLv50Strength::
    .string "Your own POKéMON know you best,\n"
    .string "and will follow your lead.\p"
    .string "Outsider POKéMON judge your field\n"
    .string "experience more carefully.\p"
    .string "Complete PROF. OAK's subquests\n"
    .string "to earn their confidence.$"

CeruleanCity_House1_Text_DefenseStatSurf::
    .string "The SOULBADGE is proof that\n"
    .string "you defeated FUCHSIA GYM's LEADER.$"

CeruleanCity_House1_Text_ObeyLv70RockSmash::
    .string "The stronger an outsider POKéMON\n"
    .string "is, the more it tests you.\p"
    .string "A strong FIELD AIDE record shows\n"
    .string "that you understand POKéMON in\l"
    .string "battle, habitats, and evolution.$"

CeruleanCity_House1_Text_SpStatsWaterfall::
    .string "The VOLCANOBADGE is proof that\n"
    .string "you defeated CINNABAR GYM's LEADER.$"

CeruleanCity_House1_Text_AllMonsWillObeyYou::
    .string "Complete enough of PROF. OAK's\n"
    .string "subquests, and even powerful\l"
    .string "outsider POKéMON will obey you.$"
