Route3_Text_TunnelFromCeruleanTiring::
    .string "Whew… I better take a rest…\n"
    .string "Groan…\p"
    .string "That tunnel from CERULEAN takes a\n"
    .string "lot out of you!$"

Route3_Text_ColtonIntro::
    .string "Hey!\n"
    .string "I saw you in VIRIDIAN FOREST!$"

Route3_Text_ColtonDefeat::
    .string "You beat me again!$"

Route3_Text_ColtonPostBattle::
    .string "There are other kinds of POKéMON\n"
    .string "than the ones you find in forests.$"

Route3_Text_BenIntro::
    .string "Hi!\n"
    .string "This rocky trail is perfect for\n"
    .string "getting stronger!$"

Route3_Text_BenDefeat::
    .string "I don't believe it!$"

Route3_Text_BenPostBattle::
    .string "MT. MOON is close now.\p"
    .string "If you train here first, the cave\n"
    .string "feels a lot less scary.$"

Route3_Text_JaniceIntro::
    .string "Excuse me!\n"
    .string "You looked at me, didn't you?$"

Route3_Text_JaniceDefeat::
    .string "You're mean!$"

Route3_Text_JanicePostBattle::
    .string "You shouldn't be staring if you\n"
    .string "don't want to battle!$"

Route3_Text_GregIntro::
    .string "The trail gets rockier from here.\n"
    .string "Step carefully!$"

Route3_Text_GregDefeat::
    .string "You found your footing!$"

Route3_Text_GregPostBattle::
    .string "MT. MOON is rougher than this.\n"
    .string "Bring sturdy POKéMON.$"

Route3_Text_SallyIntro::
    .string "That look you gave me…\n"
    .string "It's so intriguing!$"

Route3_Text_SallyDefeat::
    .string "Be nice!$"

Route3_Text_SallyPostBattle::
    .string "You can avoid battles by not\n"
    .string "letting TRAINERS see you.$"

Route3_Text_CalvinIntro::
    .string "Hey!\n"
    .string "This trail is my favorite place\n"
    .string "to test new partners!$"

Route3_Text_CalvinDefeat::
    .string "Lost!\n"
    .string "Lost! Lost!$"

Route3_Text_CalvinPostBattle::
    .string "The rocks make everyone slow down.\p"
    .string "That makes it easier to spot a\n"
    .string "TRAINER who wants a battle.$"

Route3_Text_JamesIntro::
    .string "I'll battle you with the POKéMON\n"
    .string "I just caught.$"

Route3_Text_JamesDefeat::
    .string "Done like dinner!$"

Route3_Text_JamesPostBattle::
    .string "Trained POKéMON are stronger than\n"
    .string "the wild ones.$"

Route3_Text_RobinIntro::
    .string "Eek!\n"
    .string "Did you touch me?$"

Route3_Text_RobinDefeat::
    .string "That's it?$"

Route3_Text_RobinPostBattle::
    .string "ROUTE 4 is at the foot of\n"
    .string "MT. MOON.$"

Route3_Text_RouteSign::
    .string "ROUTE 3\n"
    .string "MT. MOON AHEAD$"
