ViridianForest_Text_FriendsItchingToBattle::
    .string "I came here with some friends to\n"
    .string "catch us some BUG POKéMON!\p"
    .string "They're all itching to get into\n"
    .string "some POKéMON battles!$"

ViridianForest_Text_RickIntro::
    .string "Hey! You have POKéMON!\n"
    .string "Come on!\l"
    .string "Let's battle 'em!$"

ViridianForest_Text_RickDefeat::
    .string "No!\nCATERPIE can't hack it!$"

ViridianForest_Text_RickPostBattle::
    .string "Ssh! You'll scare the bugs away.\n"
    .string "Another time, okay?$"

ViridianForest_Text_DougIntro::
    .string "Yo!\n"
    .string "You can't jam out if you're a\l"
    .string "POKéMON TRAINER!$"

ViridianForest_Text_DougDefeat::
    .string "Huh?\n"
    .string "I ran out of POKéMON!$"

ViridianForest_Text_DougPostBattle::
    .string "That totally stinks! I'm going to\n"
    .string "catch some stronger ones!$"

ViridianForest_Text_SammyIntro::
    .string "Hey, wait up!\n"
    .string "What's the hurry? Why the rush?$"

ViridianForest_Text_SammyDefeat::
    .string "I give!\n"
    .string "You're good at this!$"

ViridianForest_Text_SammyPostBattle::
    .string "Sometimes, you can find stuff on\n"
    .string "the ground.\p"
    .string "I'm looking for the stuff I\n"
    .string "dropped. Can you help me?$"

ViridianForest_Text_AnthonyIntro::
    .string "I might be little, but I won't like\n"
    .string "it if you go easy on me!$"

ViridianForest_Text_AnthonyDefeat::
    .string "Oh, boo.\n"
    .string "Nothing went right.$"

ViridianForest_Text_AnthonyPostBattle::
    .string "I lost some of my allowance…$"

ViridianForest_Text_CharlieIntro::
    .string "Did you know that POKéMON evolve?$"

ViridianForest_Text_CharlieDefeat::
    .string "Oh!\n"
    .string "I lost!$"

ViridianForest_Text_CharliePostBattle::
    .string "BUG POKéMON evolve quickly.\n"
    .string "They're a lot of fun!$"

ViridianForest_Text_RanOutOfPokeBalls::
    .string "I was throwing POKé BALLS to\n"
    .string "catch POKéMON, and I ran out.\p"
    .string "That's why you can never have too\n"
    .string "many POKé BALLS.$"

ViridianForest_Text_ErikaLookingForRoot::
    .string "ERIKA: Oh, hello.\p"
    .string "I came to VIRIDIAN FOREST in\n"
    .string "search of an ENERGY ROOT.\p"
    .string "A root grown in this forest is said\n"
    .string "to hold wonderful healing power.\p"
    .string "I am certain one can be found\n"
    .string "somewhere nearby.$"

ViridianForest_Text_ErikaShownRoot::
    .string "ERIKA: Oh!\n"
    .string "That is just the root I had hoped\l"
    .string "to study.\p"
    .string "If I could find one of my own, I\n"
    .string "would gladly return to the GYM.$"

ViridianForest_Text_GymGuideFoundErika::
    .string "ERIKA!\n"
    .string "I am so glad I found you!\p"
    .string "And look, I found an ENERGY ROOT\n"
    .string "the way here.$"

ViridianForest_Text_ErikaChallenge::
    .string "ERIKA: How fortunate.\n"
    .string "This is almost satisfying.\p"
    .string "Before I return, may I ask you for\n"
    .string "a proper GYM challenge?\p"
    .string "With my GYM GUIDE present, the\n"
    .string "match will be official.$"

ViridianForest_Text_ErikaBattleIntro::
    .string "Very well.\n"
    .string "Let us begin.{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

ViridianForest_Text_ErikaDefeat::
    .string "Oh!\n"
    .string "I concede defeat.$"

ViridianForest_Text_ErikaAfterBattle::
    .string "ERIKA: You are remarkably strong.\p"
    .string "This battle was witnessed, so it\n"
    .string "shall stand as your GYM challenge.\p"
    .string "Please come to CELADON GYM.\n"
    .string "I will grant your reward there.$"

ViridianForest_Text_LeavingViridianForest::
    .string "LEAVING VIRIDIAN FOREST\n"
    .string "PEWTER CITY AHEAD$"
