MtMoon_B2F_Text_MiguelIntro::
    .string "Hey, stop!\p"
    .string "I'm busy checking every corner\n"
    .string "of this cave!$"

MtMoon_B2F_Text_MiguelDefeat::
    .string "Okay!\n"
    .string "I'll move along!$"

MtMoon_B2F_Text_WellEachTakeAFossil::
    .string "There are old fragments scattered\n"
    .string "all over MT. MOON.$"

MtMoon_B2F_Text_ThenThisFossilIsMine::
    .string "All right.\n"
    .string "I'll keep searching elsewhere!$"

MtMoon_B2F_Text_LabOnCinnabarRegeneratesFossils::
    .string "Far away, on CINNABAR ISLAND,\n"
    .string "there's a POKéMON LAB.\p"
    .string "They do research on regenerating\n"
    .string "fossils.$"
