SilphCo_11F_Text_ThanksForSavingMeDearBoy::
    .string "PRESIDENT: Oh, dear boy!\n"
    .string "Thank you for saving SILPH.\p"
    .string "I will never forget you saved us in\n"
    .string "our moment of peril.\p"
    .string "I have to thank you in some way.\p"
    .string "Because I am rich, I can give you\n"
    .string "anything.\p"
    .string "Here, maybe this will do.$"

SilphCo_11F_Text_ThanksForSavingMeDearGirl::
    .string "PRESIDENT: Oh, dear girl!\n"
    .string "Thank you for saving SILPH.\p"
    .string "I will never forget you saved us in\n"
    .string "our moment of peril.\p"
    .string "I have to thank you in some way.\p"
    .string "Because I am rich, I can give you\n"
    .string "anything.\p"
    .string "Here, maybe this will do.$"

SilphCo_11F_Text_ObtainedMasterBallFromPresident::
    .string "{PLAYER} obtained a MASTER BALL\n"
    .string "from the PRESIDENT!$"

SilphCo_11F_Text_ThatsOurSecretPrototype::
    .string "PRESIDENT: You can't buy that\n"
    .string "anywhere.\p"
    .string "It's our secret prototype MASTER\n"
    .string "BALL.\p"
    .string "It will catch any POKéMON without\n"
    .string "fail!\p"
    .string "You should be quiet about using it,\n"
    .string "though.$"

SilphCo_11F_Text_YouHaveNoRoomForThis::
    .string "You have no room for this.$"

SilphCo_11F_Text_ThanksForRescuingUs::
    .string "SECRETARY: Thank you for rescuing\n"
    .string "all of us.\p"
    .string "We, from the PRESIDENT down,\n"
    .string "are indebted to you.$"

SilphCo_11F_Text_GiovanniIntro::
    .string "GIOVANNI: So, you followed me\n"
    .string "from CINNABAR.\p"
    .string "SILPH's MASTER BALL is no mere\n"
    .string "product.\p"
    .string "It is control made mechanical.\n"
    .string "Command made perfect.\p"
    .string "With its plans, TEAM ROCKET will\n"
    .string "manufacture the means to reclaim\l"
    .string "MEWTWO.\p"
    .string "Stand aside, {PLAYER}.\p"
    .string "I will not allow sentiment to\n"
    .string "interrupt absolute power.$"

SilphCo_11F_Text_GiovanniDefeat::
    .string "No…\n"
    .string "The plan was flawless!$"

SilphCo_11F_Text_GiovanniPostBattle::
    .string "GIOVANNI: Without SILPH's process,\n"
    .string "the MASTER BALL cannot be produced\l"
    .string "for TEAM ROCKET.\p"
    .string "You have delayed me.\n"
    .string "Nothing more.\p"
    .string "MEWTWO exists because I demanded\n"
    .string "that power answer to me.\p"
    .string "It will answer.\n"
    .string "Or it will be made to.$"

SilphCo_11F_Text_Grunt2Intro::
    .string "Stop right there!\n"
    .string "Don't you move!$"

SilphCo_11F_Text_Grunt2Defeat::
    .string "Don't…\n"
    .string "Please!$"

SilphCo_11F_Text_Grunt2PostBattle::
    .string "So, you want to see my BOSS?$"

SilphCo_11F_Text_Grunt1Intro::
    .string "Halt! Do you have an appointment\n"
    .string "with my BOSS?$"

SilphCo_11F_Text_Grunt1Defeat::
    .string "Gaah!\n"
    .string "Demolished!$"

SilphCo_11F_Text_Grunt1PostBattle::
    .string "Watch your step…\n"
    .string "My BOSS likes his POKéMON tough!$"

SilphCo_11F_Text_MonitorHasMonsOnIt::
    .string "The monitor has POKéMON on it!$"

SilphCo_11F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "11F$"
