SilphCo_11F_Text_ThanksForSavingMeDearBoy::
    .string "PRESIDENT: Oh, dear boy!\n"
    .string "Thank you for saving SILPH.\p"
    .string "GIOVANNI failed to take the\n"
    .string "MASTER BALL plans.\p"
    .string "But before he fled, he accessed\n"
    .string "our signal research.\p"
    .string "If he combines it with old\n"
    .string "CINNABAR records, he may force\l"
    .string "MEWTWO to respond.\p"
    .string "Please, take this.\n"
    .string "If he reaches MEWTWO, you may\l"
    .string "need it.$"

SilphCo_11F_Text_ThanksForSavingMeDearGirl::
    .string "PRESIDENT: Oh, dear girl!\n"
    .string "Thank you for saving SILPH.\p"
    .string "GIOVANNI failed to take the\n"
    .string "MASTER BALL plans.\p"
    .string "But before he fled, he accessed\n"
    .string "our signal research.\p"
    .string "If he combines it with old\n"
    .string "CINNABAR records, he may force\l"
    .string "MEWTWO to respond.\p"
    .string "Please, take this.\n"
    .string "If he reaches MEWTWO, you may\l"
    .string "need it.$"

SilphCo_11F_Text_ObtainedMasterBallFromPresident::
    .string "{PLAYER} obtained a MASTER BALL\n"
    .string "from the PRESIDENT!$"

SilphCo_11F_Text_ThatsOurSecretPrototype::
    .string "PRESIDENT: You can't buy that\n"
    .string "anywhere.\p"
    .string "It's our secret prototype MASTER\n"
    .string "BALL.\p"
    .string "It was built to catch any POKéMON\n"
    .string "without fail.\p"
    .string "If GIOVANNI truly calls MEWTWO,\n"
    .string "that may be the only clean way to\l"
    .string "end this.$"

SilphCo_11F_Text_YouHaveNoRoomForThis::
    .string "You have no room for this.$"

SilphCo_11F_Text_ThanksForRescuingUs::
    .string "SECRETARY: Thank you for rescuing\n"
    .string "all of us.\p"
    .string "We, from the PRESIDENT down,\n"
    .string "are indebted to you.$"

SilphCo_11F_Text_GiovanniIntro::
    .string "GIOVANNI: So, you followed me\n"
    .string "from CINNABAR.\p"
    .string "SILPH's MASTER BALL is no mere\n"
    .string "product.\p"
    .string "It is control made mechanical.\n"
    .string "Command made perfect.\p"
    .string "With its plans, TEAM ROCKET will\n"
    .string "manufacture the means to reclaim\l"
    .string "MEWTWO.\p"
    .string "Stand aside, {PLAYER}.\p"
    .string "I will not allow sentiment to\n"
    .string "interrupt absolute power.$"

SilphCo_11F_Text_GiovanniDefeat::
    .string "No…\n"
    .string "The plan was flawless!$"

SilphCo_11F_Text_GiovanniPostBattle::
    .string "GIOVANNI: So SILPH's MASTER BALL\n"
    .string "will remain out of reach.\p"
    .string "No matter.\p"
    .string "A BALL is only one way to claim\n"
    .string "power.\p"
    .string "The device is complete enough.\n"
    .string "It will call MEWTWO to me.\p"
    .string "Once it answers, no LEAGUE,\n"
    .string "no child, and no bond will stand\l"
    .string "in my way.\p"
    .string "TEAM ROCKET, withdraw.\n"
    .string "We have what we need.$"

SilphCo_11F_Text_Grunt2Intro::
    .string "Stop right there!\n"
    .string "Don't you move!$"

SilphCo_11F_Text_Grunt2Defeat::
    .string "Don't…\n"
    .string "Please!$"

SilphCo_11F_Text_Grunt2PostBattle::
    .string "So, you want to see my BOSS?$"

SilphCo_11F_Text_Grunt1Intro::
    .string "Halt! Do you have an appointment\n"
    .string "with my BOSS?$"

SilphCo_11F_Text_Grunt1Defeat::
    .string "Gaah!\n"
    .string "Demolished!$"

SilphCo_11F_Text_Grunt1PostBattle::
    .string "Watch your step…\n"
    .string "My BOSS likes his POKéMON tough!$"

SilphCo_11F_Text_MonitorHasMonsOnIt::
    .string "The monitor has POKéMON on it!$"

SilphCo_11F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "11F$"
