SSAnne_B1F_Room1_Text_PhillipIntro::
    .string "Matey, you're walking the plank if\n"
    .string "you lose!$"

SSAnne_B1F_Room1_Text_PhillipDefeat::
    .string "Argh!\n"
    .string "Beaten by a kid!$"

SSAnne_B1F_Room1_Text_PhillipPostBattle::
    .string "When we're out at sea, jellyfish\n"
    .string "POKéMON sometimes drift by.$"

SSAnne_B1F_Room1_Text_BarnyIntro::
    .string "Even below deck, one should keep\n"
    .string "their battling form polished.$"

SSAnne_B1F_Room1_Text_BarnyDefeat::
    .string "Oh!\n"
    .string "How uncouth of me!$"

SSAnne_B1F_Room1_Text_BarnyPostBattle::
    .string "I came below deck for quiet.\p"
    .string "Instead, I found quite the capable\n"
    .string "trainer.$"
