Route12_NorthEntrance_2F_Text_RememberPokemon::
    .string "My POKéMON's ashes are stored in\n"
    .string "POKéMON TOWER.\p"
    .string "I come here when I need a quiet\n"
    .string "place to remember them.\p"
    .string "If you treat your POKéMON well,\n"
    .string "they'll return your love by working\l"
    .string "their hardest in battle.$"

Route12_NorthEntrance_2F_Text_TheresManFishing::
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "There's a man fishing!$"

Route12_NorthEntrance_2F_Text_ItsPokemonTower::
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "It's POKéMON TOWER!$"
