PokemonTower_2F_Text_HopeIntro::
    .string "Urrg… Awaa…\n"
    .string "Huhu… Graa…$"

PokemonTower_2F_Text_HopeDefeat::
    .string "Hwa!\n"
    .string "I'm saved!$"

PokemonTower_2F_Text_HopePostBattle::
    .string "The ghosts can be identified\n"
    .string "clearly now.$"

PokemonTower_2F_Text_CarlyIntro::
    .string "Kekeke…\n"
    .string "Kwaaah!$"

PokemonTower_2F_Text_CarlyDefeat::
    .string "Hmm?\n"
    .string "What am I doing?$"

PokemonTower_2F_Text_CarlyPostBattle::
    .string "Sorry!\n"
    .string "I was possessed!$"

PokemonTower_2F_Text_PatriciaIntro::
    .string "Be gone!\n"
    .string "Malevolent spirit!$"

PokemonTower_2F_Text_PatriciaDefeat::
    .string "Whew!\n"
    .string "The spirit left!$"

PokemonTower_2F_Text_PatriciaPostBattle::
    .string "The others above…\n"
    .string "They must have been possessed.$"
