RocketLeague_Arena_Text_Official::
    .string "This is the ROCKET LEAGUE arena.\p"
    .string "Only serious challengers stand\n"
    .string "under these lights.$"

RocketLeague_Arena_Text_AreYouReady::
    .string "Are you ready?$"

RocketLeague_Arena_Text_RocketDefeat::
    .string "Tch!\n"
    .string "That one is yours.$"

RocketLeague_Arena_Text_ReceivedCoins::
    .string "{PLAYER} received 250 COINS\n"
    .string "as a ROCKET LEAGUE prize.$"

RocketLeague_Arena_Text_CoinCaseFull::
    .string "Your COIN CASE is full.\p"
    .string "You couldn't receive the prize\n"
    .string "COINS.$"
