Route24_Text_JustEarnedFabulousPrize::
    .string "Congratulations! You beat our\n"
    .string "five contest TRAINERS!\p"
    .string "You just earned a fabulous prize!$"

Route24_Text_ReceivedNuggetFromRewardGiver::
    .string "{PLAYER} received a NUGGET\n"
    .string "from the challenge host!$"

Route24_Text_YouDontHaveAnyRoom::
    .string "You don't have any room!$"

Route24_Text_KeepTraining::
    .string "That was a fine run across\n"
    .string "NUGGET BRIDGE.\p"
    .string "Keep training, and keep that\n"
    .string "momentum going!$"

Route24_Text_YouAlreadyClaimedPrize::
    .string "You've already claimed your\n"
    .string "NUGGET BRIDGE prize.\p"
    .string "Keep up the good work!$"

Route24_Text_ShaneIntro::
    .string "I saw your feat from the grass!$"

Route24_Text_ShaneDefeat::
    .string "I thought not!$"

Route24_Text_ShanePostBattle::
    .string "I hid because the people on the\n"
    .string "bridge frightened me.$"

Route24_Text_EthanIntro::
    .string "Okay! I'm No. 5!\n"
    .string "I'll stomp you!$"

Route24_Text_EthanDefeat::
    .string "Whoa!\n"
    .string "Too much!$"

Route24_Text_EthanPostBattle::
    .string "I did my best. I have no regrets!$"

Route24_Text_ReliIntro::
    .string "I'm No. 4!\n"
    .string "Getting tired?$"

Route24_Text_ReliDefeat::
    .string "I lost, too!$"

Route24_Text_ReliPostBattle::
    .string "I did my best, so I've no regrets!$"

Route24_Text_TimmyIntro::
    .string "Here's No. 3!\n"
    .string "I won't be easy!$"

Route24_Text_TimmyDefeat::
    .string "Ow!\n"
    .string "Stomped flat!$"

Route24_Text_TimmyPostBattle::
    .string "I did my best. I have no regrets!$"

Route24_Text_AliIntro::
    .string "I'm second!\n"
    .string "Now it's serious!$"

Route24_Text_AliDefeat::
    .string "How could I lose?$"

Route24_Text_AliPostBattle::
    .string "I did my best. I have no regrets!$"

Route24_Text_CaleIntro::
    .string "People call this the NUGGET\n"
    .string "BRIDGE!\p"
    .string "Beat us five TRAINERS and win\n"
    .string "a fabulous prize!\p"
    .string "Think you got what it takes?$"

Route24_Text_CaleDefeat::
    .string "Whoo!\n"
    .string "Good stuff!$"

Route24_Text_CalePostBattle::
    .string "I did my best. I have no regrets!$"
