TwoIsland_House_Text_TeachMonMoveForMushroom::
    .string "I'm the POKéMON MOVE MANIAC.\p"
    .string "I know every single move that\n"
    .string "POKéMON learn growing up.\p"
    .string "I'm also a mushroom maniac.\p"
    .string "Bring me two TINYMUSHROOMS,\n"
    .string "or one BIG MUSHROOM.\p"
    .string "If you do that for me, I'll teach\n"
    .string "a move to one POKéMON.$"

TwoIsland_House_Text_WantMeToTeachMove::
    .string "Sniff, sniff…\n"
    .string "Hm! You smell of MUSHROOMS!\p"
    .string "Do you want me to teach a move\n"
    .string "to a POKéMON of yours?$"

TwoIsland_House_Text_TutorWhichMon::
    .string "Which POKéMON needs tutoring?$"

TwoIsland_House_Text_TeachWhichMove::
    .string "Which move should I teach?$"

TwoIsland_House_Text_NoMoveICanTeachThatMon::
    .string "Sorry…\p"
    .string "It doesn't appear as if I have a\n"
    .string "move I can teach that POKéMON.$"

TwoIsland_House_Text_IllNeedMushroomOrTwo::
    .string "Then, I'll need a MUSHROOM or two.\n"
    .string "What are you going to give me?$"

TwoIsland_House_Text_HandedOverTwoTinyMushrooms::
    .string "{PLAYER} handed over two\n"
    .string "TINYMUSHROOMS in exchange.$"

TwoIsland_House_Text_HandedOverOneBigMushroom::
    .string "{PLAYER} handed over one\n"
    .string "BIG MUSHROOM in exchange.$"

TwoIsland_House_Text_NeedMushroomOrTwoToLearnMove::
    .string "If your POKéMON need to learn a\n"
    .string "move, I need a MUSHROOM or two.$"

TwoIsland_House_Text_CantTeachAnEgg::
    .string "Hunh? There isn't a single move\n"
    .string "that I can teach an EGG.$"

Text_UltimateMoveThatMon::
    .string "I perfected the ultimate move of\n"
    .string "its type…\p"
    .string "But will no one take it for\n"
    .string "future use?\p"
    .string "…Hm? Hmmm!\p"
    .string "Y-you…\n"
    .string "Th-that {STR_VAR_1}…$"

Text_JustMistaken::
    .string "…No…\n"
    .string "I was just mistaken.$"

Text_AllowMeToTeachMonUltimateMove::
    .string "Oh! This is the one!\n"
    .string "This is the POKéMON!\p"
    .string "This {STR_VAR_1} is worthy of\n"
    .string "learning my ultimate move!\p"
    .string "Will you allow it?\p"
    .string "Will you allow your {STR_VAR_1} to\n"
    .string "learn my {STR_VAR_2}?$"

Text_YouRejectIt::
    .string "Gaah! You reject it?\n"
    .string "No, I won't be dissuaded!$"

Text_LetMeConferUltimateMove::
    .string "You will allow it?\p"
    .string "Then, let me confer my ultimate\n"
    .string "{STR_VAR_2} on your {STR_VAR_1}.\p"
    .string "Ggggrah-awooo!$"

Text_TaughtMove::
    .string "Gasp, gasp, gasp…\p"
    .string "I didn't think I could teach that\n"
    .string "move while I still lived…$"

Text_MakeBestUseOfMove::
    .string "I implore you to make the best\n"
    .string "use of that move and gain power!$"

Text_PassedOnEverythingIKnow::
    .string "Gasp, gasp, gasp…\p"
    .string "I have no regrets now.\n"
    .string "I've passed on everything I know.\p"
    .string "Now I can live out my life knowing\n"
    .string "my work is done.$"

Text_FeelRejuvenated::
    .string "After I passed on my knowledge to\n"
    .string "you, I felt so much relief.\p"
    .string "In fact, I feel rejuvenated,\n"
    .string "as if I were younger again!$"
