RocketLeague_ChampionsRoom_Text_GiovanniIntro::
    .string "GIOVANNI: Four victories in\n"
    .string "succession.\p"
    .string "You have earned the right to face\n"
    .string "the ROCKET LEAGUE CHAMPION.$"

RocketLeague_ChampionsRoom_Text_GiovanniDefeat::
    .string "Excellent.\p"
    .string "Your ambition has weight.$"

RocketLeague_ChampionsRoom_Text_PostBattle::
    .string "GIOVANNI: The title remains an\n"
    .string "instrument of power.\p"
    .string "Use this victory well.$"

RocketLeague_ChampionsRoom_Text_ReceivedCoins::
    .string "{PLAYER} received 1,000 COINS\n"
    .string "as a ROCKET LEAGUE prize.$"

RocketLeague_ChampionsRoom_Text_CoinCaseFull::
    .string "Your COIN CASE is full.\p"
    .string "You couldn't receive the prize\n"
    .string "COINS.$"

RocketLeague_ChampionsRoom_Text_NotReady::
    .string "The ROCKET LEAGUE CHAMPION\n"
    .string "is not waiting here yet.$"

