Route16_NorthEntrance_1F_Text_NoPedestriansOnCyclingRoad::
    .string "No pedestrians are allowed on\n"
    .string "CYCLING ROAD!$"

Route16_NorthEntrance_1F_Text_CyclingRoadIsDownhillCourse::
    .string "CYCLING ROAD is a downhill course\n"
    .string "by the sea. It's a great ride.$"

Route16_NorthEntrance_1F_Text_RentBike::
    .string "No BICYCLE?\p"
    .string "You can rent one here for Routes\n"
    .string "16, 17, and 18.\p"
    .string "The rental fee is 500.\p"
    .string "Rent a BICYCLE?$"

Route16_NorthEntrance_1F_Text_RentalStarted::
    .string "All set!\p"
    .string "Ride carefully, and return it\n"
    .string "when you leave the route.$"

Route16_NorthEntrance_1F_Text_RentalActive::
    .string "Your rental BICYCLE is ready.\p"
    .string "It can be used on Routes 16,\n"
    .string "17, and 18.$"

Route16_NorthEntrance_1F_Text_OwnBike::
    .string "You've got your own BICYCLE.\p"
    .string "You're ready for CYCLING ROAD.$"

Route16_NorthEntrance_1F_Text_ExcuseMeWaitUp::
    .string "Excuse me!\n"
    .string "Wait up, please!$"

Route16_NorthEntrance_1F_Text_HowdYouGetInGoodEffort::
    .string "How'd you get in?\n"
    .string "Good effort!$"

Route16_NorthEntrance_1F_Text_NotEnoughMoney::
    .string "You don't have enough money.$"

Route16_NorthEntrance_1F_Text_ReturnRentalBike::
    .string "Welcome back.\p"
    .string "I'll take the rental BICYCLE\n"
    .string "from here.$"
