Route16_House_Text_FoundMySecretRetreat::
    .string "Oh, dear.\n"
    .string "You've found my secret retreat.\p"
    .string "Please don't tell anyone I'm here.\n"
    .string "I'll make it up to you with this!$"

Route16_House_Text_ReceivedTM52FromGirl::
    .string "{PLAYER} received TM52\n"
    .string "from the girl.$"

Route16_House_Text_ExplainTM52::
    .string "TM52 is FLY.\n"
    .string "It's a wonderfully convenient move.\p"
    .string "Please, put it to good use.$"

Route16_House_Text_DontHaveAnyRoomForThis::
    .string "You don't have any room for this.$"

Route16_House_Text_Fearow::
    .string "FEAROW: Kyueen!$"

