Route16_House_Text_FoundMySecretRetreat::
    .string "Oh, dear.\n"
    .string "You've found my secret retreat.\p"
    .string "Please don't tell anyone I'm here.\n"
    .string "This quiet place means everything\n"
    .string "to me.$"

Route16_House_Text_ReceivedTM52FromGirl::
    .string "{PLAYER} received TM52\n"
    .string "from the girl.$"

Route16_House_Text_ExplainTM52::
    .string "Please keep this place a secret.$"

Route16_House_Text_DontHaveAnyRoomForThis::
    .string "You don't have any room for this.$"

Route16_House_Text_Fearow::
    .string "FEAROW: Kyueen!$"
