#!/usr/bin/env python3
"""Generate the active Dex roster and sort orders without renumbering saved Dex IDs."""
import argparse, re
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
def read(p): return (ROOT/p).read_text()
def sprite_table(p): return dict(re.findall(r'SPECIES_SPRITE\((\w+),\s*(\w+)\)', read(p)))
def derive():
    dex = re.findall(r'^\s*NATIONAL_DEX_(\w+),', read('include/constants/pokedex.h').split('};',1)[0], re.M)
    mapping = read('src/pokemon.c').split('static const u16 sSpeciesToNationalPokedexNum')[1].split('};')[0]
    mapped = set(re.findall(r'SPECIES_TO_NATIONAL\((\w+)\)',mapping))
    stats = dict(re.findall(r'\[SPECIES_(\w+)\]\s*=\s*\{(.*?)\}',read('src/data/pokemon/species_info.h'),re.S))
    entries = dict(re.findall(r'\[NATIONAL_DEX_(\w+)\]\s*=\s*\{(.*?)\n    \}',read('src/data/pokemon/pokedex_entries.h'),re.S))
    names = dict(re.findall(r'\[SPECIES_(\w+)\]\s*=\s*_\("([^"]+)"\)',read('src/data/text/species_names.h')))
    learns = dict(re.findall(r'\[SPECIES_(\w+)\]\s*=\s*(\w+)',read('src/data/pokemon/level_up_learnset_pointers.h')))
    active=[]; excluded={}
    for n in dex:
        if n in ('NONE','COUNT') or n.startswith('OLD_UNOWN_'): continue
        reasons=[]
        if n not in mapped: reasons.append('not mapped/retired')
        if not re.search(r'\.baseHP\s*=\s*[1-9]',stats.get(n,'')): reasons.append('no playable stats')
        if not names.get(n) or '?' in names[n]: reasons.append('missing name')
        if n not in learns or 'Empty' in learns[n]: reasons.append('missing learnset')
        if n not in entries: reasons.append('missing dex entry')
        if reasons: excluded[n]=reasons
        else: active.append(n)
    return active, excluded, entries, names, stats

def outputs():
    active,excluded,entries,names,stats=derive()
    roster='// Generated by tools/sync_active_pokedex.py; IDs stay stable for existing saves.\n'
    roster+='static const bool8 sActivePokedexSpecies[NATIONAL_DEX_COUNT + 1] =\n{\n'
    roster+=''.join(f'    [NATIONAL_DEX_{n}] = TRUE,\n' for n in active)+'};\n'
    types={k:int(v) for k,v in re.findall(r'#define TYPE_(\w+)\s+(\d+)',read('include/constants/pokemon.h'))}
    def number(n,field): return int(re.search(r'\.'+field+r'\s*=\s*(\d+)',entries[n])[1])
    def typekey(n):
        ts=re.search(r'\.types\s*=\s*\{TYPE_(\w+),\s*TYPE_(\w+)',stats[n])
        return (types[ts[1]],types[ts[2]],names[n])
    orders='// Generated by tools/sync_active_pokedex.py from the complete active roster.\n'
    for label,key,prefix in [('Alphabetical',lambda n:names[n],'NATIONAL_DEX'),('Weight',lambda n:(number(n,'weight'),names[n]),'NATIONAL_DEX'),('Height',lambda n:(number(n,'height'),names[n]),'NATIONAL_DEX'),('Type',typekey,'SPECIES')]:
        orders+=f'const u16 gPokedexOrder_{label}[] =\n{{\n'+''.join(f'    {prefix}_{n},\n' for n in sorted(active,key=key))+'};\n\n'
    report='# Active Pokédex roster\n\n'+f'{len(active)} species enabled. Existing species and Dex IDs are unchanged. Eligibility requires playable stats, a name, a learnset, and a Dex entry. Unfinished/placeholder sprites do not hide a species; this includes the Safari regional forms and unfinished fossil Pokémon. Deliberately retired species remain excluded.\n\n'
    report+='All four sort orders are generated from the same roster. Inactive IDs remain reserved for save compatibility; displayed numbering therefore retains gaps.\n\n## Excluded entries\n\n'
    report+='\n'.join(f'- {n}: {", ".join(why)}' for n,why in excluded.items())+'\n'
    return {'src/data/pokemon/active_pokedex.h':roster,'src/data/pokemon/pokedex_orders.h':orders.rstrip()+'\n','docs/active-pokedex-roster.md':report},active
if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    files,active=outputs()
    for p,data in files.items():
        if args.check: assert read(p)==data, f'Stale generated file: {p}'
        else: (ROOT/p).write_text(data)
    if args.check:
        cats=read('src/data/pokemon/pokedex_categories.h')
        covered=set(re.findall(r'SPECIES_(\w+)',cats))
        assert not set(active)-covered, f'Missing habitat entries: {set(active)-covered}'
        for name,body in re.findall(r'sDexCategory_(\w+_Page\w+)\[\]\s*=\s*\{(.*?)\}',cats,re.S):
            assert len(re.findall(r'SPECIES_',body))<=4,name
    print(f'{len(active)} active Pokémon; generated files '+('verified' if args.check else 'updated'))
