#!/usr/bin/env python3
"""Build the card's single-game acquisition roster, excluding trainer-only species.

Sources: mapped wild encounters, scripted gifts/encounters, NPC trades, Rocket
prizes, supported evolution and Route 5 breeding. Special scripted acquisitions
are explicit below. This is a source audit, not a proof of every quest's reachability.
"""
import argparse
import json
import re
from pathlib import Path
from sync_active_pokedex import derive

ROOT = Path(__file__).resolve().parents[1]

def generate():
    active = set(derive()[0])
    sources = {}
    def add(name, reason):
        if name in active:
            sources.setdefault(name, set()).add(reason)
    def read(path):
        return (ROOT / path).read_text()
    def names(text):
        return re.findall(r'SPECIES_(\w+)', text)
    scripts = list((ROOT / 'data/maps').glob('*/scripts.inc')) + list((ROOT / 'data/scripts').glob('*.inc'))
    script_text = '\n'.join(p.read_text() for p in scripts)
    # Only maps present in the build contribute wild encounters.
    maps = {json.loads(p.read_text())['id'] for p in (ROOT / 'data/maps').glob('*/map.json')}
    wild = json.loads(read('src/data/wild_encounters.json'))
    for group in wild['wild_encounter_groups']:
        if not group.get('for_maps'):
            continue
        for entry in group['encounters']:
            if entry['map'] in maps:
                for name in names(json.dumps(entry)):
                    add(name, 'Wild: ' + entry['map'])
    for p in scripts:
        for name in re.findall(r'(?:givemon|giveegg|setwildbattle|seteventmon) SPECIES_(\w+)', p.read_text()):
            add(name, str(p.relative_to(ROOT)))
    # Variable-driven gifts and the gym terminal do not use literal givemon operands.
    for name in ('BULBASAUR', 'CHARMANDER', 'SQUIRTLE', 'HITMONLEE', 'HITMONCHAN', 'PORYGON2', 'PORYGON_Z'):
        add(name, 'Starter / Dojo gift / Blaine terminal')
    prizes = read('src/shop.c').split('sRocketPrizeMons[] =')[1].split('};')[0]
    for name in names(prizes):
        add(name, 'Rocket League prize shop')
    trades = re.findall(r'\[(INGAME_TRADE_\w+)\] =\s*\{(.*?)\n    \}', read('src/data/ingame_trades.h'), re.S)
    trades = [(label, re.search(r'\.species = SPECIES_(\w+)', body)[1],
               re.search(r'\.requestedSpecies = SPECIES_(\w+)', body)[1],
               re.search(r'\.heldItem = (ITEM_\w+)', body)[1])
              for label, body in trades if label in script_text]
    # Item references in actual scripts/shop inventories, not item definitions.
    map_items = '\n'.join(p.read_text() for p in (ROOT / 'data/maps').glob('*/map.json'))
    pickup = read('src/battle_script_commands.c').split('sPickupItems[] =')[1].split('};')[0]
    items = set(re.findall(r'ITEM_\w+', script_text + map_items + read('src/shop.c') + pickup))
    stats = dict(re.findall(r'\[SPECIES_(\w+)\]\s*=\s*\{(.*?)\n    \},', read('src/data/pokemon/species_info.h'), re.S))
    for name, reasons in sources.items():
        if any(reason.startswith('Wild:') for reason in reasons):
            items.update(re.findall(r'\.item(?:Rare|Common)\s*=\s*(ITEM_\w+)', stats.get(name, '')))
    evolution_text = re.sub(r'//[^\n]*', '', read('src/data/pokemon/evolution.h'))
    evolutions = []
    for base, body in re.findall(r'\[SPECIES_(\w+)\]\s*=\s*\{(.*?)(?=\n    \[|\n};)', evolution_text, re.S):
        for method, param, target in re.findall(r'\{(EVO_\w+),\s*(\w+),\s*SPECIES_(\w+)\}', body):
            evolutions.append((base, method, param, target))
    # In-game trades evolve upon receipt even where the evolution item isn't sold.
    changed = True
    while changed:
        previous = set(sources)
        for label, received, requested, held in trades:
            if requested in sources:
                add(received, 'NPC trade: ' + label)
                for base, method, param, target in evolutions:
                    if base == received and (method == 'EVO_TRADE' or (method == 'EVO_TRADE_ITEM' and param == held)):
                        add(target, 'NPC trade evolution: ' + label)
        for base, method, param, target in evolutions:
            if base in sources and not method.startswith('EVO_TRADE'):
                if not param.startswith('ITEM_') or param in items:
                    add(target, 'Evolution: ' + base)
            # The daycare follows evolution ancestry backwards. Ditto is catchable.
            # No unavailable incense-only babies are introduced by these current links.
            if target in sources and 'DITTO' in sources:
                add(base, 'Breeding ancestry: ' + target)
        changed = set(sources) != previous
    roster = '// Generated by tools/sync_obtainable_pokedex.py; acquisition evidence is in tools/obtainable_pokedex.json.\n'
    roster += 'static const bool8 sObtainablePokedexSpecies[NATIONAL_DEX_COUNT + 1] =\n{\n'
    roster += ''.join(f'    [NATIONAL_DEX_{n}] = TRUE,\n' for n in sorted(sources)) + '};\n'
    evidence = {'required_count': len(sources), 'sources': {k: sorted(v) for k, v in sorted(sources.items())},
                'excluded': sorted(active - sources.keys())}
    return {'src/data/pokemon/obtainable_pokedex.h': roster,
            'tools/obtainable_pokedex.json': json.dumps(evidence, indent=2) + '\n'}, evidence

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    files, evidence = generate()
    for path, contents in files.items():
        if args.check:
            assert (ROOT / path).read_text() == contents, 'Stale acquisition roster: ' + path
        else:
            (ROOT / path).write_text(contents)
    print(f"{evidence['required_count']} obtainable species; {len(evidence['excluded'])} excluded")
