CeruleanCity_Text_RivalIntro::
    .string "{RIVAL}: Yo! {PLAYER}!\p"
    .string "You're still struggling along back\n"
    .string "here?\p"
    .string "I'm doing great! I caught a bunch\n"
    .string "of strong and smart POKéMON!\p"
    .string "Here, let me see what you caught,\n"
    .string "{PLAYER}!$"

CeruleanCity_Text_RivalDefeat::
    .string "Hey!\n"
    .string "Take it easy!\l"
    .string "You won already!$"

CeruleanCity_Text_RivalPostBattle::
    .string "{RIVAL}: Hey, guess what?\p"
    .string "I went to BILL's and got him to\n"
    .string "show me his rare POKéMON.\p"
    .string "That added a lot of pages to my\n"
    .string "POKéDEX!\p"
    .string "After all, BILL's world famous as a\n"
    .string "POKéMANIAC.\p"
    .string "He invented the POKéMON Storage\n"
    .string "System on PC, too.\p"
    .string "Since you're using his system,\n"
    .string "you should go thank him.\p"
    .string "Well, I better get rolling!\n"
    .string "Smell ya later!$"

CeruleanCity_Text_OhRightLittlePresentAsFavor::
    .string "Oh, yeah, right.\p"
    .string "I feel sorry for you. No, really.\n"
    .string "You're always plodding behind me.\p"
    .string "So here, I'll give you a little\n"
    .string "present as a favor.$"

CeruleanCity_Text_ExplainFameCheckerSmellYa::
    .string "A chatty gossip like you…\n"
    .string "That thing's perfect.\p"
    .string "I don't need it because I don't\n"
    .string "give a hoot about others.\p"
    .string "All right, this time I really am\n"
    .string "gone. Smell ya!$"

@ RB translation: "Heh! You're no match for my genius!"
CeruleanCity_Text_RivalVictory::
    .string "なんたって！\n"
    .string "おれは　てんさい　だからよ！$"

CeruleanCity_Text_TrainerLifeIsToughIsntIt::
    .string "You're a TRAINER, too?\p"
    .string "Collecting, battling…\n"
    .string "It's a tough life, isn't it?$"

CeruleanCity_Text_YouCanCutDownSmallTrees::
    .string "Did you know that some paths\n"
    .string "through town are easy to miss?\p"
    .string "Even if something looks blocked,\n"
    .string "there may be another way around.$"

CeruleanCity_Text_IfSlowbroWasntThereCouldCutTree::
    .string "If that SLOWBRO wasn't there, you\n"
    .string "could take the path ahead.\p"
    .string "That way, you could get to the\n"
    .string "other side.\p"
    .string "I think there's a way around it,\n"
    .string "though.$"

CeruleanCity_Text_PokemonEncyclopediaAmusing::
    .string "You're making an encyclopedia on\n"
    .string "POKéMON? That sounds amusing.$"

CeruleanCity_Text_PeopleHereWereRobbed::
    .string "The people here had a bit of\n"
    .string "trouble with their house.\p"
    .string "We're keeping an eye on things\n"
    .string "while they finish repairs.$"

CeruleanCity_Text_SlowbroUseSonicboom::
    .string "Okay! SLOWBRO!\n"
    .string "Use SONICBOOM!$"

CeruleanCity_Text_SlowbroPayAttention::
    .string "Come on, SLOWBRO, pay attention!$"

CeruleanCity_Text_SlowbroPunch::
    .string "SLOWBRO, punch!$"

CeruleanCity_Text_NoYouBlewItAgain::
    .string "No!\n"
    .string "You blew it again!$"

CeruleanCity_Text_SlowbroWithdraw::
    .string "SLOWBRO, WITHDRAW!$"

CeruleanCity_Text_HardToControlMonsObedience::
    .string "No! That's wrong!\n"
    .string "It's so hard to control POKéMON!\p"
    .string "Your POKéMON's obedience depends\n"
    .string "on your abilities as a TRAINER.$"

CeruleanCity_Text_SlowbroTookSnooze::
    .string "SLOWBRO took a snooze…$"

CeruleanCity_Text_SlowbroLoafingAround::
    .string "SLOWBRO is loafing around…$"

CeruleanCity_Text_SlowbroTurnedAway::
    .string "SLOWBRO turned away…$"

CeruleanCity_Text_SlowbroIgnoredOrders::
    .string "SLOWBRO ignored orders…$"

CeruleanCity_Text_WantBrightRedBicycle::
    .string "I want a bright red bicycle.\p"
    .string "I'll keep it at home, so it won't\n"
    .string "get dirty.$"

CeruleanCity_Text_ThisIsCeruleanCave::
    .string "This is CERULEAN CAVE.\p"
    .string "Horribly strong POKéMON live inside\n"
    .string "there.\p"
    .string "It takes a very special TRAINER to\n"
    .string "be allowed inside there.\p"
    .string "You'd have to be strong enough to\n"
    .string "become the POKéMON LEAGUE\l"
    .string "CHAMPION for starters.\p"
    .string "And, you would have to have\n"
    .string "made a great achievement.$"

CeruleanCity_Text_CitySign::
    .string "CERULEAN CITY\n"
    .string "A Mysterious, Blue Aura Surrounds\l"
    .string "It$"

CeruleanCity_Text_BikeShopSign::
    .string "Grass and caves handled easily!\n"
    .string "BIKE SHOP$"

CeruleanCity_Text_GymSign::
    .string "CERULEAN CITY POKéMON GYM\n"
    .string "LEADER: MISTY\l"
    .string "The Tomboyish Mermaid!$"
