FiveIsland_Meadow_Text_Rocket1Intro::
    .string "This area's strictly off-limits!\n"
    .string "Out, out!$"

FiveIsland_Meadow_Text_Rocket1Defeat::
    .string "Is this for real?$"

FiveIsland_Meadow_Text_Rocket1PostBattle::
    .string "You don't have any business here!\n"
    .string "Go home!$"

FiveIsland_Meadow_Text_Rocket2Intro::
    .string "There's nothing for you past here.\p"
    .string "So what brings you all this way?$"

FiveIsland_Meadow_Text_Rocket2Defeat::
    .string "That wasn't supposed to happen…$"

FiveIsland_Meadow_Text_Rocket2PostBattle::
    .string "It's better if you forget about\n"
    .string "this place.\p"
    .string "For your own sake, I mean.$"

FiveIsland_Meadow_Text_Rocket3Intro::
    .string "You'd be wasting time even if you\n"
    .string "were to get by me.$"

FiveIsland_Meadow_Text_Rocket3Defeat::
    .string "Oh, that makes me furious!$"

FiveIsland_Meadow_Text_Rocket3PostBattle::
    .string "You won't be able to get in without\n"
    .string "the passwords anyway.$"
