FourIsland_House1_Text_FatMan::
    .string "それ　ぼよーん！\n"
    .string "おまえ　おもいなあー！$"

FourIsland_PokemonCenter_1F_Text_RareIceMonsInCave::
    .string "There's a rare kind of ICE POKéMON\n"
    .string "that lives in the cave.\p"
    .string "We get a lot of visitors hoping to\n"
    .string "see that POKéMON.$"

FourIsland_PokemonCenter_1F_Text_DayCarePeopleFoundEggBefore::
    .string "Oh? A POKéMON EGG?\n"
    .string "…I have no idea.\p"
    .string "…Oh, wait. The DAY-CARE people\n"
    .string "in town were saying something.\p"
    .string "They said that they'd found EGGS\n"
    .string "before on their property.$"

FourIsland_PokemonCenter_1F_Text_NewPokemonJournalHasntArrived::
    .string "What's this?\p"
    .string "The new POKéMON JOURNAL hasn't\n"
    .string "arrived on this island?$"
