LavenderTown_HealingHouse_Text_RestHere::
	.string "Welcome, traveler.\p"
	.string "This is a HEALING HOUSE.\n"
	.string "Would you like to rest your POKéMON?$"

LavenderTown_HealingHouse_Text_Goodbye::
	.string "Take care on the roads around\n"
	.string "LAVENDER.$"

LavenderTown_HealingHouse_Text_TakeShortRest::
	.string "All right.\n"
	.string "Take a short rest here.$"

LavenderTown_HealingHouse_Text_Rested::
	.string "Your POKéMON are looking calm\n"
	.string "and lively again.$"

LavenderTown_HealingHouse_Text_RocketsDoAnythingForMoney::
	.string "TEAM ROCKET will do anything for\n"
	.string "the sake of money!\p"
	.string "There is no job too dirty, no deed\n"
	.string "too heinous, no crime too wicked!$"

LavenderTown_HealingHouse_Text_CubonesMotherKilledByRockets::
	.string "I saw CUBONE's mother trying to\n"
	.string "escape from TEAM ROCKET.\p"
	.string "She was killed trying to get away...$"

LavenderTown_HealingHouse_Text_PeoplePayForCuboneSkulls::
	.string "You know how the CUBONE species\n"
	.string "wears skulls, right?\p"
	.string "People will pay a lot for one.$"
