Route2_ViridianForest_SouthEntrance_Text_ForestComesAlive::
    .string "I'm too scared to enter\n"
    .string "VIRIDIAN FOREST.\p"
    .string "Legends tell of the forest\n"
    .string "coming alive and ensnaring the\l"
    .string "wicked, never to be seen again.$"

Route2_ViridianForest_SouthEntrance_Text_RattataHasWickedBite::
    .string "RATTATA may be small, but don't\n"
    .string "underestimate its wicked bite.\p"
    .string "Have you caught one already?$"
