CeladonCity_Hotel_Text_ThisHotelIsForPeople::
    .string "POKéMON?\n"
    .string "No, this is a hotel for people.\p"
    .string "We're full up, unfortunately.$"

CeladonCity_Hotel_Text_OnVacationWithBrotherAndBoyfriend::
    .string "I'm on vacation with my brother and\n"
    .string "boyfriend.\p"
    .string "CELADON is such a pretty city!$"

CeladonCity_Hotel_Text_BeautyRequestIntro::
    .string "I'm on vacation with my brother and\n"
    .string "boyfriend.\p"
    .string "I'm making a travel scrapbook of\n"
    .string "POKéMON people have met.\p"
    .string "Could you show me one?$"

CeladonCity_Hotel_Text_BeautyRequestMon::
    .string "I'd love to see {STR_VAR_1}.\p"
    .string "If you bring one in your party,\n"
    .string "I'll give you a little reward.$"

CeladonCity_Hotel_Text_BeautyStillLooking::
    .string "I'm still hoping to see {STR_VAR_1}.\p"
    .string "Please bring one in your party if\n"
    .string "you find it.$"

CeladonCity_Hotel_Text_BeautyRequestTookTooLong::
    .string "Oh, never mind that last POKéMON.\p"
    .string "I saw one in another trainer's\n"
    .string "photo already.$"

CeladonCity_Hotel_Text_BeautyThanks::
    .string "That's {STR_VAR_1}!\p"
    .string "Perfect, my scrapbook will look\n"
    .string "wonderful with this note.\p"
    .string "Please take this as thanks.$"

CeladonCity_Hotel_Text_BeautyBagFull::
    .string "Oh, your BAG is full.\p"
    .string "I'll hold on to the thought, then.\n"
    .string "Thank you for showing me!$"

CeladonCity_Hotel_Text_WhyDidSheBringBrother::
    .string "Why?\n"
    .string "Why did she bring her brother?$"

CeladonCity_Hotel_Text_SisBroughtMeOnVacation::
    .string "Yippee! I'm on vacation!\n"
    .string "My sis brought me along! Awesome!$"
